doc/content/articles/protonuke.article, src/protonuke/example_email, src/protonuke/smtp.go
docs: update protonuke docs to reflect file support
fixes #145
=> protonuke: add file support to external email JSON

doc/content/index.html, doc/content/static/page.css
=> doc: add contributing guide to main page links, update css widths for linkbar

doc/content/releases/minimega-2.0.article
Incomplete, merging to master so others can start to work on it.
=> docs: minimega 2.0 release notes

src/minimega/capture_cli.go, src/minimega/cc_cli.go, src/minimega/deploy.go, src/minimega/dnsmasq.go, src/minimega/dot.go, src/minimega/external.go, src/minimega/history.go, src/minimega/iomeshage.go, src/minimega/log_cli.go, src/minimega/misc.go, src/minimega/misc_cli.go, src/minimega/nuke.go, src/minimega/optimize.go, src/minimega/qcow.go, src/minimega/shell.go, src/minimega/vm_cli.go, src/minimega/vnc_cli.go, src/minimega/vyatta.go
Cleaned up the HelpShort/HelpLong for the various CLI handlers. Made some minor code cleanups as I was reading through.
=> Mad Documentation, Yo'

src/minimega/main.go, src/minimega/optimize.go, src/minimega/stats.go, src/minimega/vm.go, src/minimega/vm_cli.go, src/minimega/vminfo.go, src/minimega/vmlist.go, src/minimega/web.go
Promoted vms from struct to typedef. Renamed vmList to VMs.
Fixes #164.
=> vmList struct -> VMs map

doc/content/articles/igor.article, doc/content/articles/installing.article, doc/content/articles/powerbot.article
=> documentation: updated repo path

src/meshage/node.go
This adds a slight delay in initial discovery (MSA timeout / 2 at worst)
=> meshage: rate limit MSA to improve meshage scaling.

src/minicli/minicli.go
=> minicli: don't json encode Data field in Response.

src/minimega/vminfo.go, src/minimega/vmlist.go
=> minimega: relaunch error vms with vm start

doc/content/articles/vnc.article, doc/content/articles/vnc/vnc1.mm, doc/content/articles/vnc/vnc2.mm, doc/content/articles/vnc/vnc3.mm, doc/content/articles/vnc/vnc4.mm, doc/content/articles/vnc/vnc5.mm, doc/content/articles/vnc/vnc6.mm, src/rfbplay/main.go, src/rfbplay/transcode.go
=> rfbplay transcoding and vnc article

src/apigen/log.go, src/miniccc/log.go, src/minidoc/log.go, src/minimega/log.go, src/minimega/log_cli.go, src/protonuke/log.go, src/rfbplay/log.go, src/vmbetter/log.go
=> multiple: automatically create missing directories for logfiles

src/minimega/bridge.go, src/minimega/bridge_cli.go
=> minimega: add multiple trunk port support to bridge api

src/miniccc/client.go, src/minimega/cc_cli.go, src/ron/command.go, src/ron/server.go
minimega: throw error on nonexistent file with 'cc send'
fixes #213
=> minimega/miniccc/ron: preserve permissions on file xfer

src/minimega/bridge.go, src/minimega/bridge_cli.go
=> add 'bridge tunnel'

src/minimega/cc.go, src/minimega/vm.go, src/minimega/vm_cli.go, src/minimega/vminfo.go
Merging Jeremy's old serial code (after a few cleanups).
Diff'd the output from:
```
vm config virtio-serial 40
vm config qemu-override
```
Before and after my code cleanup -- no change. I plan to add a test to #215.
@djfritz
=> Why so serial?

src/minimega/vmconfig.go, tests/vm_config, tests/vm_config.want
Need to clear out slices before appending. Nice catch @jfktrey.
=> minimega: fix bug in `vm config`

src/minimega/bridge.go, src/minimega/vm.go, src/minimega/vm_cli.go
Fixes #198. Don't try to remove a disconnected tap.
=> minimega: fix panic in bridge code.

doc/content/static/styles.css, doc/template/action.tmpl, src/minidoc/mega.go, src/present/doc.go
=> add height parameter to .mega directive in minidoc

src/minimega/capture.go, src/minimega/dot.go, src/minimega/kvm.go, src/minimega/misc.go, src/minimega/optimize.go, src/minimega/stats.go, src/minimega/vm.go, src/minimega/vm_cli.go, src/minimega/vmlist.go, src/minimega/web.go
Renaming a bunch of stuff so that gob encoding works properly. Should resolve some of the issues with #240.
=> minimega: export for gob

src/minimega/dot.go, src/minimega/kvm.go, src/minimega/vm.go, src/minimega/vmlist.go, src/minimega/web.go
Change interface so that info takes a single mask and returns a single
value. Cleans up some code.
=> minimega: change VM Info to take single mask.

src/minimega/vm.go, src/minimega/web.go
Change code to populate and use a single slice rather than throw away a
bunch of values.
=> minimega: couple bug fixes.

misc/web/include/js/graph.js
Should take care of some of the UI weirdness in the last commit.
=> fix for small UI glitches

src/minimega/command_meshage.go
=> minimega: add namespace, port to mesh status api

src/minimega/kvm.go, src/minimega/vm.go, src/minimega/vm_cli.go, src/minimega/vmconfig.go, src/minimega/vmlist.go, src/minimega/web.go
Made some changes to how the VM code works so that it's a little easier
to add other types of VMs. Adding some more documentation for newer
functionality.
=> minimega: vm cleanup.

build.bash, misc/python/genapi.py, misc/python/template.py, misc/python/test_minimega.py, test.bash
Generated API files now contain minimega version, per @bjwrigh's request.
=> python: better versioning

src/minimega/web.go
=> Fix for VNC urls 404ing

src/minimega/kvm.go, src/minimega/vm.go, src/minimega/web.go
If the VM is not running, don't try to grab a screenshot from it.
=> minimega: fix #273.

src/minimega/command_socket.go, src/minimega/kvm.go, src/minimega/main.go, src/minimega/misc.go, tests/vm_launch_noblock, tests/vm_launch_noblock.want
Lots of refactorings to properly use locks and hopefully eliminate the
chances of a race condition when calling `launch noblock` and then
immediately starting the VM.
=> minimega: refactored the launch code. Fixes #209.

doc/content/releases/minimega-2.1.article
=> filled in some of the 2.1 release article

doc/content/releases/minimega-2.1.article
=> update 2.1 release notes.

doc/content/index.html
=> documentation: add a space. Smallest commit?

src/minimega/kvm.go, src/minimega/vm.go, src/minimega/vm_cli.go, src/minimega/vmlist.go
Merge `vm info kvm` info `vm info`.
=> minimega: fix #289.

src/minimega/cli.go
Turns out commands could run at the same time since we dropped the
command lock before the command actually completed. Fixed now.
=> minimega: fix concurrency bug.

src/minilog/minilog.go, src/minilog/minilog_test.go, src/minimega/log_cli.go
=> minimega: add log filter api

misc/web/css/minimega.css, misc/web/index.html, misc/web/js/glue.js
Change "machine list" to "vm list" and add fields for taps and IP4 IP6 addrs.
Also move the navbar to the top.
=> Web adjustments

src/minimega/cc.go, src/minimega/cc_cli.go, src/minimega/kvm.go, src/minimega/main.go, src/minimega/vm.go
This is untested, but I'd like a quick review. 
@jcrussell
=> minimega: remove cc start,serial api, make cc start at launch

src/minimega/kvm.go
=> minimega: fix static cc port in kvm vms

src/minimega/misc.go, src/minimega/vm.go
=> minimega: add check for allocated mac address on vm config net

src/minimega/misc.go
=> minimega: simplify allocatedMac()

src/minimega/bridge.go
from http://github.com/sandia-minimega/minimega/commit/69fcabee7bca70ce6d8aeedac8ccc7e4edbda6fa#diff-1219fd3dcfc7e4c077a86de95d193778R835
@jcrussell
=> minimega: fix regression in ContainerTapCreate() 

src/minimega/disk.go
=> minimega: add `disk create` API.

src/meshage/node.go, src/minimega/meshage.go, src/ron/client.go, src/ron/ron.go, src/ron/server.go
=> add version checks to minimega, miniccc

doc/content/articles/file.article, src/goreadline/goreadline.go, src/iomeshage/handler.go, src/iomeshage/iomeshage.go, src/minimega/cli.go, src/minimega/iomeshage.go
Add tab completion to file: prefix, and fix a few previously unknown bugs in iomeshage.
Also do proper autocompletion for all completion enabled APIs in goreadline.
@jcrussell @floren
=> tab completion with file: and iomeshage fixes

misc/vmbetter_configs/miniccc_container.conf, misc/vmbetter_configs/miniccc_container_overlay/init, src/vmbetter/main.go, src/vmbetter/targets.go
misc: add miniccc_container vmbetter config
@jcrussell @floren
=> vmbetter: add -rootfs flag for building container rootfs images

src/vmbetter/main.go
Not sure how this slipped past. 
@floren
=> vmbetter: -rootfs should be a bool

src/minimega/container.go
=> minimega: always use absolute path when invoking minimega containers

src/minimega/container.go, src/minimega/main.go
=> minimega: use a minimega-specific cgroup mount instead of /sys/fs/cgroup

src/minimega/dnsmasq.go, src/minimega/external.go
Add options to configure running dnsmasq instances. Still need to add commands to delete these configs, but it's a start.
=> Dnsmasq options

src/minimega/misc_cli.go
Read no longer acquires the command lock for its whole duration -- it
releases and aquires it for each command that it runs. This allows the
web interface (and other interfaces to minimega) to continue to work
even when we are reading a long file.
Fixes #358.
=> minimega: read took a chill pill

src/minimega/external.go, src/rfbplay/main.go
=> rfbplay: fix pathnames on ffmpeg transcoding

src/minimega/disk.go
fixes #336
@bjwrigh @floren @jcrussell
=> minimega: add optional mount options to `disk inject`

src/minimega/container.go, src/minimega/kvm.go
minimega: filter link local addresses in vm info for containers
@jcrussell
=> minimega: fix cc path for kvm vms

src/minimega/kvm.go
@jcrussell @djfritz 
I blame Fritz.
=> minimega: fix serial port paths

src/minimega/bridge.go, src/minimega/container.go, src/minimega/kvm.go, src/minimega/vm.go
=> minimega: fix container relaunch and flush

src/minimega/cli.go, src/minimega/dot.go, src/minimega/vm.go, src/minimega/web.go
Stealing code from namespaces to make sure we don't try to grab the cmdLock if we already have it.
=> minimega: fix #378

misc/vmbetter_configs/ccc_host_ovs.conf, misc/vmbetter_configs/ccc_host_ovs_overlay/init
Also add support for mellanox drivers.
@floren
=> update ccc image for a systemd free environment

src/minimega/container.go, src/minimega/main.go
=> fix state check on restarting containers

src/minimega/bridge.go, src/minimega/container.go, src/minimega/kvm.go, src/minimega/main.go
=> add grouped openvswitch del-tap operations by adding a tap reaper.

CONTRIBUTORS, src/minimega/container.go, src/minimega/kvm.go
=> Remove deferred logging

src/ipmac/ipmac.go, src/minimega/container.go, src/minimega/kvm.go
fixes #393 
@jcrussell @floren
=> remove race in ipmac

src/minimega/cli.go
Fixes #394. Make sure to send from a goroutine to avoid deadlock.
=> minimega: fix deadlock in processCommands.

src/protonuke/http.go
len(m.Pix) is actually 1024*768*4
=> protonuke: properly fill the httpImage

doc/content/articles/vyatta/vyattaconfig.mm, src/minimega/disk.go
=> doc/minimega: fix minor errors

src/ron/server.go
=> additional error filtering on ron connections

src/minimega/container.go, src/minimega/vm_cli.go, src/minimega/vmconfig.go
=> add vm config preinit

src/rfbplay/server.go
=> rfbplay: add time offset to url

src/minicli/builtins.go
Need to forward the filtered resps rather than the original resps...
=> minicli: fix .filter

src/minimega/vmlist.go
Fix deadlock when there's a duplicate VM name. Fixes #427.
=> minimega: port fix from namespace branch.

src/protonuke/http.go
Protonuke had a long-standing bug where requesting /12345/image.png
would return an HTML page rather than image.png as expected. This
was due to the way image handlers work in Go's http lib. This fixes
that behavior and also makes the client give more information when
logging GET requests.
=> protonuke: fix http/https handlers and timing logs

src/minimega/cc.go, src/minimega/main.go
=> minimega: make the cc port a configurable flag

src/minitunnel/minitunnel.go
=> minitunnel: add locks around register/unregister TID

src/minimega/vm.go, src/minimega/vm_cli.go, src/minimega/vmconfig.go, src/minimega/vmlist.go, src/minitest/main.go, tests/vm_config.want, tests/vm_config_net.want, tests/vm_tags, tests/vm_tags.want
_Merge after #440._
Change default print behavior for vmConfigSlice to print an empty string when the slice is empty.
Changed minitest to print an empty line when it reads an empty line.
Updated all tests accordingly.
=> minitweaks to minimega/minitest.

src/minimega/vm_cli.go
Forgot to add to list of patterns.
=> minimega: add `clear vm config cpu`.

misc/web/css/minimega.css, misc/web/index.html, misc/web/js/glue.js, src/minimega/web.go
Fix for #298 : Connect button is no longer shown for non-kvm machines
Adds a bit of documentation to glue.js
Stylesheet tweaks
Speedups for the Firefox performance issues mentioned in #315 (base64-encoded images are now generated server-side)
=> Fixes for #298 and #315

doc/content/articles/tutorials/cc.article, doc/content/articles/tutorials/cc/process.mm, doc/content/articles/tutorials/cc/serial.mm, doc/content/articles/tutorials/cc/start.mm
=> doc: update cc tutorial

doc/content/articles/minitest.article
Give an overview of minitest and the test cases.
=> doc: add minitest article.

doc/content/articles/contributing.article, doc/content/articles/file.article, doc/content/articles/igor.article, doc/content/articles/installing.article, doc/content/articles/powerbot.article, doc/content/articles/protonuke.article, doc/content/articles/tutorials/cc.article, doc/content/articles/tutorials/quickstart.article, doc/content/articles/tutorials/vmbetter.article, doc/content/articles/usage.article, doc/content/articles/vmtypes.article, doc/content/articles/vnc.article, doc/content/articles/vyatta.article, doc/content/releases/minimega-2.2.article
=> 2.2 release

doc/content/index.html
=> doc: update index.html with 2.2 release

src/minidoc/dir.go
minidoc now checks to make sure there is at least one shown file in a
directory before listing it as a sub-directory.
Accidentally killed the previous commit for this (#463).
=> minidoc: only display non-empty dirs

src/ranges/ranges.go, src/ranges/ranges_test.go
Removed some ugly code in ranges to reduce memory/cpu overhead.
=> ranges: replaced ugly code.

src/minicli/minicli.go
Truncate the history stored in minicli to a maximum size. Developers can
tweak the maximum as needed or disable limit entirely, if needed.
=> minicli: limit history size

src/minimega/command_meshage.go, src/minimega/main.go
=> minimega: change nameshpace flag to context

src/gopcap/gopcap.go
Removed double free in gopcap.NewPCAP. Fixes #493.
=> gopcap: fix double free.

src/minimega/misc_cli.go
`validate` reads a mm script and validates the syntax of the commands
therein. Only checks syntax and not semantics.
=> minimega: add `check` flag to `read`

misc/daemon/minimega.conf
whoops, missed this last time... s/NAMESPACE/CONTEXT/
Fixes #511.
=> misc: update conf.

src/minicli/handler.go, src/minicli/minicli.go, src/minicli/pattern.go, src/minicli/validate.go, src/minifuzzer/log.go, src/minifuzzer/main.go
Uses the `-cli` flag to figure out the list of commands that it can run.
Randomly select patterns and then generates the command string to match.
Little scared to test it on my workstation...
=> minifuzzer: new tool to fuzz minimega.

src/minimega/capture_cli.go
Update help text for capture API.
=> minimega: fix #520

doc/content/articles/file.article, src/minimega/cli.go, src/minimega/iomeshage.go, src/minimega/misc.go
Add preprocessor for http:// and https://. Gutted the file:
preprocessor. Closes #514.
=> minimega: add new preprocessor

src/minimega/cc_cli.go, src/ron/client.go, src/ron/command.go
Add wildcard support to `cc process kill`. Fixes #489.
Going to test this today.
=> minimega: add `cc process kill all`

CONTRIBUTORS, src/minicli/builtins.go, src/minimega/main.go
Fixed a small formatting issue and a misnomer for the `-cli` flag.
=> Little fixes

src/minidoc/minidoc.go
Now you can specify which host to listen on, if you're so inclined.
=> minidoc: change -port to -server

src/minimega/namespace.go
Can't use hostTapDelete in Namespace.Destroy since it tries to query and
update the active namespace. Instead, call the methods to delete the tap
manually. Fixes #546.
=> minimega: fix deadlock in namespace

src/minimega/capture.go, src/minimega/container.go, src/minimega/dot.go, src/minimega/kvm.go, src/minimega/vm.go, src/minimega/vmconfig_cli.go, src/minimega/vmlist.go, src/minimega/web.go, tests/vm_uuid.want
Fix a bunch of smaller things that I didn't like about the VM interface.
Need to test after #553 gets merged.
=> minimega: fix VM nits

src/bridge/bridge.go, src/bridge/mirror.go, src/bridge/tap.go, src/minimega/bridge.go, src/minimega/kvm.go
Created a tuntap rather than letting ovs create the interface for us.
Capture now seems to work. Fixes #545.
=> minimega/bridge: fix capture

src/minimega/namespace.go, src/minimega/vmlist.go, src/vlans/vlans.go
Tired of seeing some of these...
=> minimega/vlans: smarter log levels

CONTRIBUTORS, src/gonetflow/gonetflow.go
fixes https://github.com/sandia-minimega/minimega/issues/558
=> gonetflow: fix off by one error

src/minimega/misc_cli.go
Fix documentation based on #560. Simplify code by using forward.
=> minimega: update read API

src/ron/server.go
Flipped sign on reaper. Fixes #564.
=> ron: fix expiration calculation

src/protonuke/http.go, src/protonuke/smtp.go
Close smtp connections. Disable http(s) keep alives.
=> protonuke: tweaks

src/minimega/cc_cli.go
fixes #583 
File output code was never reached, needed to move into the filepath walker.
@floren @jcrussell
=> minimega: fix cc responses output

src/minimega/cc.go
=> minimega: fix race in miniccc tag updating

src/minimega/container.go, src/minimega/kvm.go, src/minimega/router_cli.go, src/minimega/vmlist.go
Small bug fixes to CC VM registration, flag parsing, and container killing.
=> minimega: bug fixes

src/minimega/cc.go, src/ron/ron.go, src/ron/server.go
=> minimega/ron: remove updateTags function literal in favor of just calling vm.SetTag

src/minimega/container.go, src/minimega/kvm.go, src/minimega/main.go, src/minimega/vm.go
Pass flags to the shim so that CGROUP_ROOT is correct when you change the minimega base directory.
Also fix the locking with cloned VMs.
Getting close to booting...
=> minimega: make it work

src/minimega/vm_cli.go
This was out of date enough to be pretty confusing.
=> minimega: update vm launch help

src/minimega/container.go, src/minimega/kvm.go, src/minimega/vm.go, src/minimega/vm_cli.go, src/minimega/vmlist.go, tests/vm_config_save, tests/vm_config_save.want
=> minimega: kill `vm save` api

src/minimega/cc_cli.go, src/minimega/disk.go, src/minimega/iomeshage.go, src/minimega/namespace.go
Prepend all commands from Namespace.Launch with the namespace. This
ensures that we invoke the cliPreprocessor.
Updates #555.
=> minimega: cliPreprocessor improvements

misc/web/js/glue.js, src/minimega/container.go, src/minimega/kvm.go, src/minimega/vm.go, src/minimega/vnc.go, src/minimega/web.go
Reverts sandia-minimega/minimega#599
This breaks the build. Shame on you @jcrussell
=> Revert "minimega: add VNC shim"

misc/vmbetter_configs/miniccc_virtio_overlay/init
=> vmbetter: fix vmbetter config init

misc/daemon/minimega.conf, misc/daemon/minimega.init
Can now configure the filepath with MM_FILEPATH.
Fixes #618
=> misc: add filepath to config

misc/web/js/glue.js, src/minimega/container.go, src/minimega/kvm.go, src/minimega/vm.go, src/minimega/vnc.go, src/minimega/web.go
Fixed import issue that somehow occurred when we merged #599. Reverts #612.
Wasn't able to duplicate #611.
=> minimega: retry #599

src/minimega/vm.go
Add container fields to `vm info` columns. Reorder things so that they
make some sense... also update `vm summary` to mirror the same order.
=> minimega: `make it weird for everyone`

src/dns/dnsutil/util.go, src/dns/example_test.go, src/dns/msg_generate.go, src/dns/privaterr_test.go, src/dns/types_generate.go
Make sure all references to github.com/miekg/dns are instead dns.
Fixes #630.
=> dns: fix vendorizing

src/minimega/vmconfig_cli.go
=> minimega: fix vm config net help

src/minimega/cc_cli.go, src/ron/client.go, src/ron/command.go
KillAll processes by name. Updates #644.
Should work... need to test though.
=> minimega/ron: add killall functionality

src/minimega/main.go, src/minimega/misc_cli.go
We're so stable, we need an uptime API.
=> minimega: add uptime

doc/content/articles/tutorials/vmbetter.article
Fixes old mini references
Missing dependencies
Unstable->Stable
Fixes bug with Ubuntu
=> Update vmbetter documentation

src/protonuke/hosts.go, src/protonuke/http.go, src/protonuke/protonuke.go, src/protonuke/smtp.go
Three improvements:
* add `-httpgzip` flag
* return 202 on POST
* use stdlib to parse hosts (and remove broadcast host)
* remove second 0 from alpanum
=> protonuke: improvements

src/minimega/web.go
Fixes #649 -- error changed from not kvm to something else that we
weren't filtering.
=> minimega: suppress container warnings

src/minimega/command_socket.go
Keep reading from the response channel even if the client leaves to
ensure that if something acquired a lock and blocked on the channel
send, we don't deadlock.
Tested on six nodes:
```
for i in $(seq 2500); do ./minimega -e mesh send all cc exec ls; done
./minimega -e mesh send all cc commands
```
I ran (and killed) the second command multiple times, seeing the log message: `command client disconnected without waiting for responses`. minimega didn't deadlock.
=> minimega: read all responses even if client leaves

src/minimega/container.go
Race involving vm.thaw returning a non-nil error as cmd.Wait() set the
err to nil. Got rid of shared err, pass it over channel instead.
=> minimega: fix race in containers

misc/vmbetter_configs/minirouter.conf, misc/vmbetter_configs/minirouter_overlay/init
=> add minirouter vmbetter config for building non-container minirouters

src/minilog/minilog.go, src/minimega/log_cli.go
minilog: add syslog helper
minimega: add syslog output and API
fixes #687
@jcrussell
=> multiple: add basic syslog support

src/minitunnel/minitunnel.go, src/minitunnel/minitunnel_test.go, src/minitunnel/mux.go
Refactored minitunnel to restore sanity to the world of tunneling.
Passes `go test -race minitunnel` -- not tested elsewhere.
Updates #666.
=> minitunnel: refactoring

src/minicli/command.go, src/minicli/handler.go
Avoid duplicating work, saves time when parsing large files.
=> minicli: improve performance

src/minimega/container.go
Set the default hostname for containers to the VM name. Fixes #702.
=> minimega: default hostname is VM name

misc/appengine/update-files.sh, src/minidoc/flags.go, src/minidoc/minidoc.go
=> misc: fix appengine build after vendorizing source

src/miniccc/client.go, src/miniccc/commands.go, src/miniccc/files.go, src/miniccc/heartbeat.go, src/miniccc/main.go, src/miniccc/mux.go, src/minimega/cc.go, src/minimega/cc_cli.go, src/ron/client.go, src/ron/command.go, src/ron/ron.go, src/ron/server.go, tests/cc, tests/cc.want, tests/cc_filter.want, tests/epilog
Improve cc compatibility with namespaces. Added a new and comprehensive
test of interaction between cc and namespaces that we can now pass.
Fixes #710, #712.
Need to do a bigger test of this.
=> ron/miniccc/minimega: more refactoring

src/minimega/vmconfig_cli.go
Include command to list network devices in help.
=> minimega: update vm config net help

src/minicli/minicli.go, src/miniclient/client.go
=> miniclient/minicli: clean up fatal log

misc/vmbetter_configs/ccc_host_ovs.conf
Include netcat-openbsd instead of regular netcat. Add curl.
=> misc: update ccc host image

doc/content/articles/igor.article, doc/content/articles/namespaces.article, doc/content/articles/powerbot.article, doc/content/articles/protonuke.article, doc/content/articles/router.article, doc/content/articles/usage.article
Updating the documentation. Checking over each article for consistency in prompts for shell/minimega examples, and fleshing out / updating information when needed.
=> Doc update

doc/content/articles/vnc.article, doc/content/articles/vnc/vnc1.mm, doc/content/articles/vnc/vnc10.mm, doc/content/articles/vnc/vnc11.mm, doc/content/articles/vnc/vnc12.mm, doc/content/articles/vnc/vnc2.mm, doc/content/articles/vnc/vnc3.mm, doc/content/articles/vnc/vnc4.mm, doc/content/articles/vnc/vnc5.mm, doc/content/articles/vnc/vnc6.mm, doc/content/articles/vnc/vnc7.mm, doc/content/articles/vnc/vnc8.mm, doc/content/articles/vnc/vnc9.mm, src/minimega/kvm.go, src/minimega/vnc.go, src/minimega/vnc_cli.go, src/minimega/vnc_playback.go, tests/vnc, tests/vnc.want
Per our discussion at the last minimeeting:
- Added the ability to inject vnc commands even if there is no playback currently running.
- Added the ability to inject LoadFile events from the cli. If there is no playback currently running a new vnc playback will be created.
=> vnc injection

src/minimega/container.go, src/minimega/nuke.go
=> minimega: unfreeze containers on nuke and a few cosmetic fixes

doc/content/articles/usage.article, doc/content/static/article.css
Biggest change is to CSS; this makes the h1/h2/h3 more distinct, and fixes
some indentation problems. Also does everything in units of 'em'.
=> doc: update css and minor usage.article fixes

src/minimega/cc.go, src/minimega/router.go, src/minimega/router_cli.go, tests/epilog, tests/router, tests/router.want, tests/router_ospf, tests/router_ospf.want, tests/router_routes, tests/router_routes.want
=> multiple: update cc, router bugs, fix minirouter tests

misc/vmbetter_configs/miniccc_virtio.conf, misc/vmbetter_configs/miniccc_virtio_overlay/init
Remove non-existent netcat6 package and add netcat-openbsd.
=> misc: update miniccc_virtio config

src/minimega/bridge_cli.go, src/minimega/main.go, src/minimega/vlans_cli.go, src/minimega/vm_cli.go
Bandaid for #600 -- log a warning and stop the panic.
=> minimega: don't panic when completing in -attach

src/minimega/misc_cli.go
"do we ever care about minimega uptime?"
=> minimega: kill the uptime API

src/minimega/main.go
Left dangling from killing uptime API.
=> minimega: Remove unused started global.

src/minimega/vnc_playback.go
=> minimega: ignore blank lines in VNC replay

misc/vmbetter_configs/minirouter_container.conf, misc/vmbetter_configs/minirouter_container_overlay/init, misc/vmbetter_configs/minirouter_container_overlay/preinit
Added minirouterfs via container.
=> misc: vmbetter for minirouterfs

src/bridge/qos.go, src/minimega/qos_cli.go
Use only netem, for all constraints: rate, loss, delay
Make constraints stackable
Auto-sizing of LIMIT parameter for netem
=> minimega: qos fix, and make constraints stackable

src/minicli/builtins.go, src/minicli/minicli.go, src/minimega/cli.go
Elevate preprocessor to minicli so that it can apply to builtins:
minimega$ echo $HOME
/root
minimega$ .record false echo $HOME
/root
Fixes #760. Need to test that this doesn't break anything.
=> minimega/minicli: elevate preprocessor

src/minimega/vnc_playback.go, src/minimega/vnc_record.go
=> minimega: made vnc command parsing more robust

src/miniccc/client.go, tests/cc_io, tests/cc_io.want
fixes #775 
@floren @jcrussell
=> miniccc: add buffered channels in mux loop

CONTRIBUTORS, misc/vmbetter_configs/ccc_host_ovs.conf, misc/vmbetter_configs/default_amd64.conf, misc/vmbetter_configs/miniccc_virtio.conf
I have a note that @jcrussell  wanted to add Curl to the default_amd64 config file. This pr is to capture that request.
=> Add curl to default fs

src/minimega/disk.go, tests/disk, tests/disk.want
Works ~99% of the time! Good find Jason.
Supersedes #791.
=> minimega: use ioctl and partx to rescan devices

src/minimega/external.go
Make sure we have 3.18+ for overlayfs. Improved version parsing to
remove trailing characters.
Fixes #792, #793.
Tested on debian jessie/stretch, ubuntu 14.04, and fedora 24.
=> minimega: add kernel version check

misc/vmbetter_configs/minirouter_overlay/init, src/minimega/router.go
Update init and set explicit path.
=> misc: minirouter working with vmbetter

misc/vmbetter_configs/miniccc_container_overlay/init, misc/vmbetter_configs/miniccc_virtio_overlay/init
misc/vmbetter_configs/miniccc_container_overlay/init
misc/vmbetter_configs/miniccc_virtio_overlay/init
=> Adding explicit path values to PATH export

src/bridge/bridge.go, src/bridge/ipmac.go
Get rid of Error logs when destroying bridge.
=> bridge: silence errors

doc/content/index.html, doc/content/releases/minimega-2.3.article
Add the release notes for 2.3.
=> minimega: release 2.3

src/minicli/builtins.go, src/minicli/command.go, src/minicli/minicli.go, tests/builtins, tests/builtins.want
Prevents over-zealous preprocessor. Fixes #576.
=> minicli: add .preprocess builtin

src/minicli/handler.go, src/minicli/minicli.go, src/miniclient/client.go, src/minimega/bridge_cli.go, src/minimega/cli.go, src/minimega/command_socket.go, src/minimega/main.go, src/minimega/vlans_cli.go, src/minimega/vm_cli.go
Send suggestions over the -attach connection. Fixes #600.
=> minimega/minicli/miniclient: support completion over -attach

src/minimega/log_cli.go, src/minimega/misc_cli.go
To simplify clearing out minimega state.
Blocking on #834.
=> minimega: add `clear all` API

src/goreadline/goreadline.go, src/minimega/bridge.go, src/minimega/cli.go, src/minimega/command_socket.go, src/minimega/iomeshage.go, src/minimega/main.go, src/minimega/meshage.go, src/minimega/vm_cli.go
Add `all` to completion options. Complete from `f_iomBase`. Complete terms beginning with '$'.
Fixes #824, #826, #831.
=> minimega: complete improvements

src/minifuzzer/main.go, src/vncdrone/vncdrone.go
Pass string instead of minicli.Command.
=> minifuzzer/vncdrone: fix for miniclient change

src/minimega/main.go
Change broke too many things.
Fixes #839. Reopens #824.
=> minimega: rollback Chdir to iombase

misc/web/js/glue.js, src/minimega/vm.go, src/minimega/vm_cli.go, src/minimega/web.go, tests/builtins, tests/builtins.want
=> minimega: add time in state to vm info and web interface

src/minimega/container.go, src/minimega/kvm.go, src/minimega/vmlist.go
VMs that share his name inherit his unstoppable will.
=> minimega: vince is unstoppable

src/bridge/bandwidth.go
Rx/Tx are reversed for host vs VM. Use weighted moving average instead
of flat average so that the bandwidth numbers adjust faster.
=> bridge: fix bandwidth

src/minimega/main.go
@jcrussell please test before submitting prs.
=> minimega: fix the build

src/minimega/namespace_cli.go
=> minimega: fix conflict in nsmod handlers

src/minidoc/flags.go, src/minidoc/minidoc.go
=> minidoc: fix appengine build

src/igor/show.go
Fix concurrent map write to nodes. Concat'ing strings is slow so use
bytes.Buffer. Move findReservation to preprocessing step.
=> igor: fix concurrent map write, faster runShow

src/passwordify/external.go, src/passwordify/main.go
Add passwordify, which lets you set a root password and (if desired) authorized_keys to an initramfs.
=> Passwordify

src/miniccc/uuid_windows.go
=> miniccc: fix broken window uuid handler

misc/vmbetter_configs/ccc_host_ovs.conf, misc/vmbetter_configs/ccc_host_ovs_overlay/etc/ssh/sshd_config, misc/vmbetter_configs/ccc_host_ovs_overlay/init, misc/vmbetter_configs/ccc_host_ovs_overlay/lib/x86_64-linux-gnu/libreadline.so.6, misc/vmbetter_configs/default_amd64.conf, src/vmbetter/main.go, src/vmbetter/overlays.go
In #842, we added support for CPU quotas which requires the cpu,cpuacct
cgroup. Adding this to our host images.
=> misc: add cpu,cpuacct to cgroups

src/igor/show.go
Way faster and simpler code. Fixes #881.
=> igor: replace sync/ping with nmap

src/bridge/container.go, src/bridge/tap.go, src/minimega/kvm.go, tests/vm_lifecycle_net, tests/vm_lifecycle_net.want
Make sure that we can restart VMs without error. Added minitest.
=> bridge/minimega: fix bug with restarting VMs

src/minimega/container.go
=> minimega: don't exit on the lack of dmi for uuid bind mounting in containers

src/minimega/router.go
=> minimega: add missing \n

src/miniclient/client.go, src/minimega/cli.go, src/minimega/command_socket.go
Fixes issues with completion including env variables and file path
completion. Closes #938.
=> minimega: fix completion

misc/web/templates/_layout.tmpl, misc/web/templates/console.tmpl, misc/web/terminal.html, src/miniweb/handlers.go, src/miniweb/main.go, src/vendor/github.com/peterh/liner/line.go
_WIP: Suggestions welcome._
Added minimega console. Mostly functional. Terminal width is a bit
wonky. Tabbed completion doesn't work. minimega location is hardcoded to
bin/minimega.
Updates #871
=> miniweb: add minimega console

misc/web/vnc.html
Tunnel path moved from /tunnel/ to /ws/tunnel/.
=> web: fix tunnel path

.travis.yml
=> travis: add go 1.9

src/minimega/container.go, src/minimega/kvm.go, src/minimega/vm.go, src/minimega/vm_cli.go
Quick addition of the qemu pid to the vm info output.
=> minimega: add pid to vm info

src/protonuke/ftpdriver.go, src/vendor/versions
Unreachable code and non-gofmt'd code, plus out of date vendors file.
=> protonuke: fix some errors that snuck in before we started using Travis

src/minimega/vmconfig_cli.go
=> minimega: update `vm config net` help

src/minimega/disk.go
minimega can't fetch backing files if they are outside the files
directory so warn if the user tries to make a snapshop of an image
outside the files directory. Fixes #941.
=> minimega: warn if disk is outside files

src/minimega/container.go
Add helper to mkdir and then mount for containers. Fixes #957.
=> minimega: add mkdirMount

src/miniccc/plumber.go, src/miniplumber/miniplumber.go
miniplumber: don't deal with vias on write if meshage isn't being used
fixes #927
@mkunz7 @floren
=> miniccc: don't use local miniplumber writers

misc/web/xterm.js/dist/xterm.js, src/minimega/container.go, src/minimega/fifo.go, src/minimega/mutablemultiwriter.go
Intended to satisfy #709 
So far multiple terminals open works, and when you open a new terminal it plays back some scrollback so you don't have a blank screen. "screenshot" is going to be very difficult and needs to be punted.
=> multiple container terminals & scrollback

doc/content/articles/developer/locking.article, doc/content/articles/miniweb.article, doc/content/articles/tutorials/quickstart.article, doc/content/articles/usage.article, doc/content/articles/vnc.article, doc/content/screenshots/index.html, doc/content/tools.html
=> doc: add miniweb article

src/minimega/capture_cli.go, src/minimega/cli.go, src/minimega/qos_cli.go, src/minimega/vm_cli.go
Only complete the "vm" field and only add wildcard for commands that
support it.
=> minimega: fix bug with VM completion

doc/content/articles/igor.article, src/igor/command.go, src/igor/del.go, src/igor/igor.sh, src/igor/main.go, src/igor/network.go, src/igor/network_arista.go, src/igor/power.go, src/igor/sampleconfig.json, src/igor/schedule.go, src/igor/setup.sh, src/igor/show.go, src/igor/sub.go, src/igor/sudo-rule, src/igor/util.go
Fixes some bugs with how reservations worked in a Cobbler environment,
fixes a bug in allocating VLANs.
Adds the ability to power nodes on and off.
Adds additional logging to a file.
Adds limits to how many nodes a reservation can contain and how long
a reservation can run.
=> igor: fix bugs, add power control

src/minimega/command_meshage.go
=> minimega: print unlimited rather than MaxInt64

src/igor/main.go, src/igor/util.go
Adding the option to print version information for igor
=> igor: add version option

tests/cc, tests/cc.want, tests/cc_io, tests/cc_io.want, tests/container_lifecycle, tests/container_lifecycle.want, tests/container_volumes, tests/container_volumes.want, tests/vm_lifecycle_cc, tests/vm_lifecycle_cc.want, tests/vm_lifecycle_net, tests/vm_lifecycle_net.want
To minicccfs. Long live minicccfs.
=> tests: rename containerfs

misc/vmbetter_configs/miniccc_container.conf
=> misc: remove unneeded packages from minicccfs

src/miniclient/client.go, src/miniweb/handlers.go, src/miniweb/main.go, src/miniweb/miniclient.go, src/miniweb/tabular.go
miniweb now automatically tries to reconnect to minimega whenever it is
disconnected. If it cannot reconnect, it logs a warning and tries again
for during the next request.
@bjwrigh
=> miniweb: automatically reconnect

src/igor/power.go, src/igor/schedule.go, src/igor/sub.go
This is a check-in for the following igor issues:
1. using both -w and -n should result in some kind of error and not be ignored
2. Reservations were being made slightly <=1min into the future
3. power.go - wrong log call used
4. Adding in time units to -t allowing # days specified
=> Igor: Fixes and Updates

src/igor/sub.go
Fix time parsing without a unit. Reflow help text so that it's not half
formatted to a width and half not. Fix some logging statements.
=> igor: fix time parsing, reflow help, fix logging

misc/web/js/graph.js
Updated connect URL in graph to match the new VM connect URL.
=> web: fix connect URL

src/minimega/vnc_cli.go
Record read from iomBase unless the path is absolute. Fixes #1023.
=> minimega: prepend iombase to vnc files

src/minimega/vnc.go, src/minimega/vnc_cli.go, src/minimega/vnc_playback.go, src/minimega/vnc_record.go
Fixes a bunch of potential issues with the vnc playback code including leaked file descriptors and race conditions. Updates #1021.
@mkunz7: could you try this with some of your VNC-heavy experiments?
=> minimega: rewrite vnc playback

doc/content/articles/tutorials/cc.article
Document how to start miniccc with systemd. Should probably include a
Windows example too.
=> doc: add instructions to start miniccc with systemd

misc/vmbetter_configs/carnac_host.conf, misc/vmbetter_configs/carnac_host_overlay/etc/locale.gen, misc/vmbetter_configs/carnac_host_overlay/etc/ntp.conf, misc/vmbetter_configs/carnac_host_overlay/etc/ssh/sshd_config, misc/vmbetter_configs/carnac_host_overlay/init, misc/vmbetter_configs/carnac_host_overlay/lib/x86_64-linux-gnu/libreadline.so.6, misc/vmbetter_configs/ccc_host_ovs.conf, misc/vmbetter_configs/ccc_host_ovs_overlay/etc/locale.gen, misc/vmbetter_configs/host.conf
=> misc: new vmbetter conf for carnac

src/ron/command.go
Hopefully to prevent weird bugs in the future.
=> ron: make deep copies of commands

src/iomeshage/iomeshage.go, src/minimega/iomeshage.go
For example, `file delete *.qcow`. Fixes #972.
=> iomeshage: support file delete <glob>

src/igor/sub.go
Add Seek after computing hashes. Move copy-if-new to separate function.
Document future TODOs to prevent "leaking" kernel/initrds.
=> igor: fix empty kernel/initrds

src/igor/sub.go
Bug fix; using -n flag caused a panic when checking the nodes
=> igor: BoundCheck Fix

.travis.yml, check.bash, src/minimega/namespace.go
Build with latest 1.8 and 1.9 versions. Add 1.10.
=> travis: bump go versions

src/minimega/kvm.go
Change VM state to paused when we migrate it. Remove error that is not
actually an error.
=> minimega: fix issues with `vm migrate`

src/igor/schedule.go
Adding log information for when igor does schedule file initialization.
=> igor: trivial: adding log info

misc/web/js/graph.js
=> miniweb: fix graph node coloring.

src/minimega/misc_cli.go
Clear plumb state in clear all.
=> minimega: clear plumb in all

misc/appengine/update.bash
Need to export GOPATH and run in quiet mode to eliminate prompt.
=> misc: another appengine fix

src/igor/backend.go, src/igor/cobbler.go, src/igor/config.go, src/igor/del.go, src/igor/extend.go, src/igor/io.go, src/igor/main.go, src/igor/power.go, src/igor/reservation.go, src/igor/runner.go, src/igor/sub.go, src/igor/tftp.go
- Create Backend interfaces to abstract cobbler vs tftp (and allow for
a mock backend).
- Clean up running things in parallel and add support for limits on the`
number of concurrent subcommands (probably useful for cobbler).
- Add power cycle.
- Log when there's an encoding error on the reservations or schedule.
- Merge schedule and reservations file. Keep reservations.json for external tools.
Needs testing... :D
=> igor: refactoring

src/igor/cobbler.go, src/igor/del.go, src/igor/external.go, src/igor/io.go, src/igor/main.go, src/igor/reservation.go
Found and fixed issues while trying to deploy. Better cleanups of
existing cobbler profiles/distros. Use Installed flag in reservation
rather than file on disk. Use a separate lock file.
=> igor: more fixes

src/minilog/logger.go, src/minilog/minilog.go, src/minilog/ring.go, src/minimega/log_cli.go
Add in-memory log ring that stores at most <size> messages. Can be
dumped with "log ring".
=> minimega/minilog: add log ring

src/minimega/disk.go, tests/disk, tests/disk.want
`disk` should error when there is more than one partition. Fix cleanup.
=> minimega: bug fixes to `disk`

src/igor/cobbler.go
When deleting a profile, reset nodes to the default profile so that
cobbler will let us delete the profile.
=> igor: reset nodes to default profile

src/igor/io.go
Changing the location of the tempdata file to TFTPRoot/igor/tmp data to ensure write permission
=> igor: change tmp file write location

src/minimega/scheduler.go
Resolve localhost to $hostname.
=> minimega: fix `vm config schedule localhost`

src/minilog/logger.go
Calldepth was different, uncombine code.
=> minilog: fix issue with filenames

doc/content/articles/nat.article, doc/content/articles/newvm.article, doc/content/articles/router.article, doc/content/articles/tutorials/cc.article, doc/content/articles/vmtypes.article, misc/get_containerfs.bash
Minor updates to fix rough edges. Remove references to prebuilt
container image (outdated). Add new articles for NAT and creating a new
VM image.
=> doc: updates, new articles

src/minimega/main.go, src/minimega/misc.go, src/minimega/netconfig.go, src/minimega/vmconfiger_cli.go, src/vmconfiger/templates.go
Need to write slices using join instead of fmt.
=> minimega/vmconfiger: fix bug in ns snapshot

doc/content/articles/installing.article
Link wasn't showing up properly.
=> doc: fix nit

misc/web/novnc/app/ui.js
Really stupid (but effective) fix for 1144 until we can figure out
something better.
=> novnc: hax for 1144

src/igor/main.go
Make sure that we are running as igor and not some other user.
=> igor: check euid

src/igor/show.go
implemented a proper fix for the issue with alignment in tabwriter by making the color values a consistent length.
=> igor: tabwriter colors

src/igor/notify.go
Changing the admin check to align with the checks we do in sub so that notify can run
=> igor: notify admin check

src/igor/show.go
alignment take 3: user name edition
=> igor: alignment pt. 3

src/minimega/vm_cli.go
If Jason says "That's interesting", ignore.
=> minimega: fix bug in vm tag

misc/web/templates/montage.tmpl, src/miniweb/main.go
Page to tile vm screenshots with parameters for layout and refresh rate.
=> miniweb: add montage

src/vmbetter/external.go, src/vmbetter/targets.go
Fixes #1119.
@activeshadow: can you test with your build environment?
=> vmbetter: replace fdisk with sfdisk

src/igor/show.go
adding a line in the igor show output listing the unreserved nodes.
=> igor: show - list unsubbed nodes

src/minimega/capture_cli.go, src/minimega/cc_cli.go, src/minimega/disk.go, src/minimega/dnsmasq.go, src/minimega/misc.go, src/minimega/misc_cli.go, src/minimega/nuke.go, src/minimega/qos_cli.go, src/minimega/vm_cli.go
Fixed issue with "unreachable".
=> minimega: fix capture

.travis.yml, src/minimega/main.go, src/minirouter/dnsmasq.go, src/minirouter/socket.go, src/vmconfig/vmconfig.go
Add go 1.11 as build version. Fix new go vet issues. Fix for change to
scanner in go 1.11.
=> various: add go 1.11 build

src/vmbetter/post.go
Was having issues building images that relied on these.
=> vmbetter: add /dev and /proc to chroot

tests/epilog, tests/plumbing_basic, tests/plumbing_basic.want
Added a sleep to basic tests and cleared plumbing after each test.
=> miniplumber: Fixed dropped message errors with plumbing minitests.

src/igor/extend.go
Changed checks to allow admins to extend at anytime
=> igor: Allow Admin to extend any time

src/iomeshage/handler.go, src/iomeshage/iomeshage.go
Keep trying to generate a unique TID until the end of time. This
*should* complete after a few tries -- int63 is a big space.
=> iomeshage: i think i can (generate a unique TID)

src/minimega/container.go
Automatically create the volume source if it does not exist.
=> minimega: create volume source if not exists

src/igor/reservation.go, src/igor/reservation_test.go, src/igor/sync.go
Reconfigure switchports based on active reservations.
=> igor: add igor sync arista

src/igor/stats.go, src/igor/stats_test.go
Added new test for reading logs, Changed out Verbose displays data, corrected a bug on reading new reservations
=> igor: stats - verbose changes, added help, other fixes

doc/content/articles/file.article
=> doc: add tar: prefix

tests/distributed/vm_colocated_errors, tests/distributed/vm_colocated_errors.want
Fix typo in test. Forgot to add .want before.
=> tests: fix test for `vm config colocate`

src/minimega/container.go
Replace obscure overlayMount error with filesystem does not exist error.
=> minimega: bail if filesystem does not exist

src/minitest/main.go
Should fix the unreliable `tap_mirror_vm` test.
=> minitest: sort errors

.travis.yml, LICENSE.gimme, doc/content/articles/installing.article, misc/vmbetter_configs/buildbot.conf, misc/vmbetter_configs/buildbot_overlay/usr/local/bin/gimme
Trim support for older versions (1.8 and 1.9).
=> various: Go 1.11

misc/appengine/app.yaml
Upgrade HTTP requests to HTTPS.
=> appengine: use HTTPS

misc/web/novnc/app/ui.js
Reverts sandia-minimega/minimega#1145
On our back to pre-v1.0.0 for noVNC.
=> Revert "novnc: hax for 1144"

src/minimega/kvm.go, src/minimega/vm.go
Add symlinks to the VM instance directories.
=> VM instance path symlinks

misc/vmbetter.bash, src/vmbetter/main.go, src/vmbetter/targets.go
Add option to override target name.
Add vmbetter.bash to simplify building images.
=> vmbetter: wrapper and new option

src/minimega/vmconfig.go
=> minimega: error if schedule host not in namespace

misc/web/js/glue.js, src/minimega/diskconfig.go, src/minimega/kvm.go, src/minimega/namespace.go, src/minimega/vm.go, src/minimega/vmconfig_cli.go, tests/diskconfig, tests/diskconfig.want
Prevent `DiskConfig.SnapshotPath` from getting copied over upon `vm config clone`.
=> minimega: fix #1300 vm config clone regression

src/igor/show.go
Add a line to `igor show`'s usage for the `-json` flag. @csymonds
=> igor: Add help for 'igor show -json'

src/minimega/command_socket.go
=> minimega: correctly deal with connection error. fixes #1324

src/minimega/cc_cli.go
fixes #1340
@jcrussell @jasoncontrib @csymonds
=> minimega: populate response with cc response <prefix>

src/minimega/cc_cli.go
bring this part of the api up to speed with the other parts
@jasoncontrib
=> minimega: allow searching on vm name, uuid in cc tunnel

misc/web/templates/newvm.tmpl, src/minimega/vm_cli.go, src/miniweb/handlers.go, src/miniweb/main.go
Add a page to miniweb to launch a saved VM config. Add option to specify VM config name with `vm launch`.
=> minimega,miniweb: launch specific vm config, new VM page

src/ranges/ranges.go, src/ranges/ranges_test.go, src/ranges/trie.go
Find repeated patterns in suffixes and collapse them.
=> ranges: fun with recursion

doc/content/articles/ospf_cost.article, src/minimega/router.go, src/minimega/router_cli.go, src/minirouter/bird.go
Add capability to configure OSPF options and article describing tweaking
the costs of different interfaces.
=> minimega,minirouter: configure OSPF options

src/minimega/cc_cli.go
Makes it easier for scripts to figure out what command ID they issued.
Fixes #1344
=> minimega: shove cc command ID into Data

src/minimega/namespace.go
=> minimega: warn if 4+ disks

src/minimega/external.go
Warn if not present. Fixes #1230.
=> minimega: check for kvm module

src/minimega/container.go, src/minimega/kvm.go, src/minimega/vm.go
Needs to be exported and Copy'd to make it across mesh.
Fixes #1333
=> minimega: fix VM PID

src/minimega/container.go, src/minimega/kvm.go, src/minimega/vm.go, src/minimega/vms.go
create VM instance path symlinks for containers, too
=> minimega: fix #1336

tests/distributed/plumbing_basic.want, tests/distributed/plumbing_miniccc.want, tests/plumbing_basic.want
Pending discussion in #1313 this fixes #1313
=> update want file for plumbing_basic test

doc/content/articles/installing.article, doc/content/articles/publications.article, doc/content/index.html, doc/content/releases/minimega-2.6.article, doc/template/layout.tmpl, packaging/debian/minimega/DEBIAN/control
_WIP: Do not merge, yet_
Start of the v2.6 release process.
=> doc: first cut of 2.6 release notes

src/igor/config.go
=> Igor: Add the requested duration to max duration error

doc/content/articles/tutorials/vmbetter.article
=> Updates to vmbetter documentation

src/minimega/cc_cli.go
=> minimega: fix vm name check for rtunnel

misc/vmbetter_configs/carnac_host.conf
Updating the ib library package in apt for narnac_host.conf in vmbetter configs
=> vmbetter: Updating the ib library package in apt

doc/content/articles/newvm.article
=> doc: add multi-stage builds to vmbetter docs

src/igor/util.go
=> Igor logging

src/vncdrone/vncdrone.go
=> vncdrone: rewrite to support different phases of execution, better name matching

.gitignore, build.bash, doc.bash, lib/setup.py, packaging/debian/build.bash, src/pyapigen/template.go
Resolves https://github.com/sandia-minimega/minimega/issues/1412
=> minimega: package python bindings

misc/daemon/minimega.conf, misc/daemon/minimega.init, packaging/debian/minimega/DEBIAN/postinst
Resolves https://github.com/sandia-minimega/minimega/issues/1413
=> minimega: create minimega group in deb package and use it in init script

doc/content/articles/installing.article, doc/content/index.html, doc/content/releases/minimega-2.7.article, packaging/debian/minimega/DEBIAN/control
Start of the v2.7 release process.
=> doc: Release 2.7 notes

doc/content/articles/download.article, doc/content/articles/installing.article, doc/template/layout.tmpl, src/version/version.go
Adding a downloads page. 
Minor fix on link menu. 
Removed the version file which was added previously in error.
=> doc: Download page for minimega.org

src/vendor/golang.org/x/crypto/ssh/doc.go, src/vendor/golang.org/x/crypto/ssh/terminal/util.go
Fixed the vetting issue that is caused with newer versions of Go
=> protonuke: Fixed go vet issue

.github/workflows/docker.yml, docker/Dockerfile, docker/README.md, docker/docker-compose.yml, docker/minimega.service, docker/miniweb.service
- Update docker files
- Add automatic minimega docker build workflow for Github container registry (Actions)
=> Update docker files

src/ron/server.go
In commit dd04c33f I introduced a bug in the ron server code that handles serial cc connections -- failing to protect maps accessed concurrently with their associated mutexes -- that would randomly manifest itself into race conditions.
=> miniccc: fix map race conditions in ron server

src/ron/server.go
minor change. Changed handshake logging for reties to debug as its expected behavior to fail until client is ready again
=> Changed handshake logging for miniccc

cmd/minimega/container.go, cmd/minimega/kvm.go, cmd/minimega/netconfig.go, cmd/minimega/vm.go, cmd/minimega/vmconfig_cli.go, internal/bridge/ovs.go, internal/bridge/tap.go
Add `qinq` option to VM network specification config that sets the VLAN mode to `dot1q-tunnel` for the network tap in Open vSwitch.
=> [minimega] Support QinQ between VMs

cmd/minimega/kvm.go, cmd/minimega/vmconfiger_cli.go
Copy of #1500 
From Jacob -- 
> This PR adds a configuration option to switch between xHCI and EHCI for the USB controller. Only one will be enabled per VM and by default xHCI is used.
> 
> To disable xHCI and use EHCI instead (as before), add vm config usb-use-xhci false to the VM's config.
> 
> This should fix two issues:
> 
>     Issues observed for Windows VMs in phenix when both EHCI and xHCI are present
>     Backwards compatibility for certain use cases that cannot add support for xHCI (e.g., pre-2010 VMs)
>
=> Adding config option for switching from xHCI to EHCI for USB controller

cmd/minimega/vm.go, cmd/minimega/vm_cli.go
Adds xhci flag to vm info. @jacdavi -- can you double check?
=> [minimega] Adding usb flag to vm info

internal/vnc/playback.go
=> remove error reported at end of every vnc play

cmd/minimega/kvm.go, internal/ron/command.go, internal/ron/server.go, misc/uminirouter/build.bash, tests/cc_filter_vm_info.want, tests/cc_io, tests/cc_io.want, tests/epilog, tests/router, tests/router.want, tests/router_bgp, tests/router_bgp.want, tests/router_ospf, tests/router_ospf.want, tests/router_static, tests/router_static.want
Updated several test `.want` files as well as some inconsistent behavior in minimega.
Test that are still failing:
`vm_add_nic`
tests in `tests/distributed`
=> [minitest] fix some tests

cmd/minimega/disk.go
Small fix for recent PR #1545 
During development I changed rebasing to make the new image relative to the first. However, in doing so I didn't double check that a rebase onto "" (e.g., make the image independent) still worked. This PR fixes that issue
=> fix error when rebasing onto no backing image

docker/start-minimega.sh
Use `OVS_HOST_IFACE` env variable to auto add a host Ethernet interface(s) to an OVS bridge. Note that the OVS bridge to add the interface(s) to must be specified.
The format of the env variable value is: `<bridge>:<port>[,<port>,...]`
Single Interface Example (where bridge name is "phenix"): `OVS_HOST_IFACE=phenix:eth0`
Multi Interface Example (where bridge name is "phenix"): `OVS_HOST_IFACE=phenix:eth0,eth1,eth2`
=> feat: auto add host iface(s) to OVS bridge via env variable
