packaging/debian/build-package.sh

This is the last bit to complete the script for building a Debian package. Just run the script from the packaging/debian directory and it will create a .deb

Finish package building process

---

src/minicli/builtins.go
src/minicli/minicli.go

Added inverted filter (field!=value). Also added a `MustCompile` method
that runs CompileCommand and calls log.Fatal if there was an error.
Fixes issue #153.

minicli: updated .filter, new API.

---

doc/content/releases/minimega-2.0.article
misc/python/genapi.py
misc/python/test_minimega.py

The python scripts no longer have to be run inside of the misc/python/ directory, and I updated the release document.

describe python API changes, plus small tweak

---

doc/content/articles/igor.article
doc/content/articles/powerbot.article
doc/content/articles/quickstart.article
doc/content/articles/usage.article
doc/content/naming.article
doc/content/releases/minimega-2.0.article
doc/content/tools.html
doc/content_templates/api.template
src/igor/README
src/igor/main.go
src/powerbot/README
src/powerbot/powerbot.go

We need to use the same capitalization and naming conventions everywhere. I created naming.article to define those conventions, then went through and enforced them everywhere.

documentation: define naming conventions and apply them across the repo

---

src/minimega/bridge_cli.go
src/minimega/main.go
src/minimega/misc.go
src/minimega/vm_cli.go

Make sure users don't name vms/taps/bridges reserved words. Currently,
the only reserved word is the wildcard: `all`.
Fixes #111.

minimega: check for reserved words.

---

doc/content/articles/vmbetter.article

A little tutorial that tells you how to use vmbetter to make a custom livecd. I did it as a livecd because that's useful outside the context of VMs, but in the end we still use minimega to test the ISO.

documentation: added a tutorial on vmbetter

---

src/minimega/vm.go
src/minimega/web.go

Work arounds for not all VM state being stored in the VM struct.
Fallback on the Tabular data from minicli.Response to populate VM info
fields that are dynamically generated (ip, ip6, cc_active). This code
should be deleted as soon as the state for these is moved into the VM
struct.
Fixes #175

minimega: dirty hacks.

---

src/minicli/builtins.go

.columns wasn't altering the Header for responses where Tabular was nil
which lead to mismatched Header columns. Changed it so that we always
update the Header (if it's not nil).

minicli: fixes 187.

---

src/minicli/builtins.go
src/minicli/command.go
src/minicli/minicli.go
src/minimega/cli.go
src/minimega/command_meshage.go
src/minimega/command_socket.go
src/minimega/dot.go
src/minimega/misc_cli.go
src/minimega/web.go

Added new built-ins: `.record` that controls whether subcommands get
recorded in the history. This allows us to `mesh send` commands and omit
them from the local history, as needed for things like web.

Fixes #222.

---

src/minicli/minicli_test.go
src/minimega/qcow_test.go

Renamed CompileCommand -> Compile. Fixes #227.

minimega/minicli: fix unit tests.

---

src/ranges/ranges.go
src/ranges/ranges_test.go

Works correctly for single character names/IDs. Fixes #258.

ranges: fixed off-by-one bug.

---

src/meshage/node.go

Fixes #244. Don't allow meshage to connect to itself.

meshage: disallow mesh dial yourself.

---

src/igor/sub.go

I must have just forgot to put this in, all the framework was there.
Specify -c "<command line appends>" to add arguments to the kernel command
line.
Fixes #257

igor: add support for kernel commandline appends.

---

src/minimega/kvm.go
src/minimega/misc.go
src/minimega/vm.go
src/minimega/vm_cli.go
src/minimega/vmlist.go
src/minimega/web.go

This is intended to fix #252. It maintains compatibility with the
old "vm screenshot" command while allowing you to say this:
vm screenshot 0 file /dev/null
vm screenshot 0 file /dev/null 100
Instead of writing out the screenshot file at the deepest level, I
pass back a slice of bytes containing the png data, then write
it out in vm_cli's cliVmScreenshot function. Previously, we were
writing to the file, then reading that back out into the response's
Body field, which made it fail when you give /dev/null as a file.

minimega: rework screenshotting

---

src/minimega/kvm.go
src/minimega/vm.go
src/minimega/vm_cli.go
src/minimega/vmlist.go
src/minimega/vmstate.go
tests/vm_netmod
tests/vm_netmod.want

When a network is disconnected, clear the name of the bridge. Split network connect/disconnect into VM code so that we can lock properly.
Closes #184.

Improved VM net command

---

src/minimega/bridge_cli.go
src/minimega/capture_cli.go
src/minimega/cc_cli.go
src/minimega/cli.go
src/minimega/command_meshage.go
src/minimega/deploy.go
src/minimega/dnsmasq.go
src/minimega/dot.go
src/minimega/external.go
src/minimega/history.go
src/minimega/iomeshage.go
src/minimega/log_cli.go
src/minimega/main.go
src/minimega/misc_cli.go
src/minimega/nuke.go
src/minimega/optimize.go
src/minimega/qcow.go
src/minimega/shell.go
src/minimega/stats.go
src/minimega/vm_cli.go
src/minimega/vnc_cli.go
src/minimega/vyatta.go
src/minimega/web.go

Move all the minicli handler registration out of init functions and into
a single function. This allows us to use the logging framework which
isn't available until after logSetup.

minimega: centralize minicli handler registration

---

src/minimega/main.go

Needs to happen before -cli flag is processed.

minimega: move up logSetup and cliSetup.

---

src/minimega/init_test.go

Need to register handlers before trying to run tests. Fixes #310.

minimega: call logSetup and cliSetup before tests.

---

doc/content/articles/file.article
src/iomeshage/iomeshage.go
src/meshage/message.go
src/minimega/cli.go
src/minimega/iomeshage.go
src/minimega/misc_cli.go

Also added a file transfer article.
This feature allows using "file:" anywhere on the command line to transfer files to the local node. file: blocks until the file is transferred. This makes it possible to do things like:
vm config disk file:foo.qcow2
vm config disk
[/tmp/minimega/files/foo.qcow2]
@floren @jcrussell @mkunz7 @bjwrigh

add file: prefix to invoke iomeshage anywhere

---

misc/web/js/glue.js
misc/web/js/graph.js

Wherever you can look at info for a VM, it's likely that you'll want to interact directly with that VM. Now, in the network graph, when you click a VM it will add a VNC

web: add VNC links to the network graph

---

src/minimega/cli.go

Don't release the cmdLock until we've forwarded responses from the
wrapped commands.

minimega: fix locking.

---

src/minimega/vnc.go

In addition to the existing PointerEvent and KeyEvent in VNC playback,
files can now include a LoadFile directive. This will cause the specified
file to be loaded and played. The format follows the usual VNC playback
format, e.g.:
0:LoadFile,browse_slashdot.vnc
10000000000:LoadFile,/home/john/recordings/reboot_windows.vnc
The filenames may be relative to the location of the current file,
or they can be absolute. Timestamps are honored as usual.

minimega: allow scripted multi-file VNC playback

---

src/igor/sub.go
src/minidoc/dir.go

Use filepath.Join rather than string concat. Fixes #349.

igor/minidoc: fixing bad filepath joins.

---

src/minimega/misc.go

Whoops, wrong arg to format string. Should fix #359, needs testing but someone took all the nodes.

minimega: fix #359.

---

src/minimega/kvm.go

Filter out the IPv6 link local address for `vm info`.

minimega: remove link local from VM IPv6 column.

---

misc/daemon/minimega.init

This makes commands that assume the CWD is $MINIMEGA_DIR (such as the "web" command) work when minimega is run as a daemon.

update init script to launch minimega with the correct working directory

---

src/minimega/vm.go
src/minimega/vm_cli.go
src/minimega/vmlist.go

Remove two races caused by `vm launch ... noblock`:
1. Need to create copy of `vmConfig` before running the next command (in case the next command changes `vmConfig`).
2. Need to block on `vm start all` (and other vm target commands) until all outstanding `vm launch ... noblock` commands have finished creating vms.
Note: this is a cleaner fix than the one that was pushed to @djfritz's fork.

minimega: fix noblock issues.

---

src/minitunnel/minitunnel.go
src/minitunnel/minitunnel_test.go

There was a race in minitunnel -- if you forwarded a port and used it
immediately, before the TID was registered, then some of the data would get
lost causing the tests to hang. Moved spawning goroutine to after registering
the TID to fix. Ran tests for ten minutes with no issues.
Also, rewrote tests so that we don't call T.FailNow from separate goroutines as
per the [documentation](https://golang.org/pkg/testing/#T.FailNow).

minitunnel: fix race.

---

src/minimega/deploy.go

Rather than use a random suffix, append the unix timestamp. This allows
you to figure out what the latest binary is without checking `ls -l`.

minimega: change deploy suffix.

---

misc/web/js/glue.js
misc/web/tilevnc.html
src/minimega/web.go

If you go to /tilevnc on the web interface, you can view all the VNC screens at once with no additional information. Works best on Chrome, Firefox uses a lot of CPU.

Add /tilevnc to web interface

---

src/protonuke/generate_cert.go
src/protonuke/protonuke.go

With the -httptlscert and -httptlskey flags, you can specify
your own certificate instead of having protonuke generate one.
Note that you must specify both.
@djfritz

protonuke: add custom certificate flags (issue #418)

---

src/protonuke/http.go

Without this, protonuke's http and https threads can end up hung on a read if something goes weird in the connection.

protonuke: Add timeouts to http.

---

src/minicli/pattern.go
src/minicli/validate.go

@jcrussell Is there any issue with exporting `itemType`? I have it redefined it in the Python API generator, but this seems like a better option.
Everything still builds for me, and tests are passing.

Add Is__() methods to patternItem

---

src/minimega/container.go

cgroup mounts appear to save subdirectory state across mount/umount. This was news to me. This breaks a lot of expectations in new cgroup mounts all over the containers implementation. To fix, we add a cgroup directory cleaner in ContainerInit() and in containerNuke(). 
Basically we just remove, depth-first, all directories in the cgroup mount.
@cdshann

minimega: add directory cleanup in cgroup mount

---

src/minimega/vm.go
src/minimega/vm_cli.go
src/minimega/vmconfig.go
src/minimega/vmlist.go
tests/vm_tags
tests/vm_tags.want

Allows you to configure tags for all newly launched VMs. Fixes #429.

minimega: adding `vm config tag`.

---

src/minimega/disk.go
tests/disk
tests/disk.want

Relative paths should always be relative to /files/, not a mixture of /files/ and CWD. Adding tests to make sure we can create/snapshot/inject images.

minimega: fixes for disk API.

---

src/minimega/bridge.go
tests/taps_lifecycle
tests/taps_lifecycle.want

Changed defunctTaps from a slice to a map so that we can omit printing
of defunctTaps. This removes a race if we call `tap delete all` and then
immediately call `tap`.
Updated simple lifecycle test for taps.

minimega/tests: fix tap tests.

---

src/minimega/vm_cli.go
src/minimega/vmlist.go
tests/vm_uuid
tests/vm_uuid.want

Enforce that UUIDs are unique, at least on the local node. Add test to
make sure that we don't allow launch VMs with duplicate UUIDs.
Fixes #444.

minimega/tests: enforce UUID uniqueness.

---

src/minimega/container.go

A race exists between killing a container, giving up the vm lock, and the goroutine that watches for the container to exit. When the watching goroutine exits, it grabs the vm lock and asserts the new vm state (error, quit...). It's possible that the CLI can issue a kill twice before this goroutine has a chance to set the state. The fix is just to set the state in the kill routine proper.
@jcrussell look at the first commit in this PR. I had a longer solution that actually made more sense for containers, but it didn't mirror the functionality in the kvm implementation (which doesn't have this race fyi). I opted to keep this similar just for maintainability's sake.

minimega: fix race in container kill

---

misc/web/js/glue.js

Set style rather than node attr. Tested on Chrome/Firefox.

web: fix hide connect button on non-kvm VMs.

---

src/minidoc/minimega.go

strip components that cannot built in appengine.
fixes #455
@jcrussell

minidoc: copy miniclient code into minidoc for local connections

---

src/minidoc/minidoc.go

fixes #361
@jcrussell I don't actually know why this fixes this issue, but it does. This flag shouldn't even exist in the appengine build...
Doesn't really matter though, as this flag should be false by default anyway.

minidoc: make exec flag false by default

---

src/minimega/namespace.go

The following commands would crash minimega:
namespace foo nsmod add-host localhost
namespace foo vm launch kvm 1
namespace foo vm launch
Because the active namespace was reverted before `vm`launch` was
completed (asynchronously). Copied the active namespace to the local
scope to fix.

minimega: fix #467.

---

src/minimega/cli.go
src/minimega/container.go
src/minimega/kvm.go
src/minimega/namespace.go
src/minimega/vm.go
src/minimega/vm_cli.go

Much saner locking so that we can:
* block on `vm start all` while `vm launch ... noblock` launches things
in the background
* block on `vm launch` while the scheduler runs
Removes vmLaunch lock and instead pre-locks the VMs on creation. This
ensures that Launch() is the first operation called on a VM (otherwise
there will be a deadlock).
Updates #472.

minimega: fix #469.

---

src/minimega/main.go
src/minimega/misc_cli.go

Add `debug memory` and `debug cpu` APIs to dump profiling information
about minimega.
Updates #478

minimega: add profiling to `debug` API

---

src/minimega/misc.go

Use net.ParseMAC rather than a regular expression. Cleaner and faster:
BenchmarkIsMac           50000             30745 ns/op
BenchmarkIsMac2        3000000               521 ns/op
BenchmarkIsMacNet     10000000               160 ns/op
Second benchmark uses a pre-compiled regular expression.

minimega: simplify isMac.

---

src/protonuke/http.go
src/protonuke/protonuke.go

Undo some timing changes I'd made; we want to only count http/https "pageloads" rather than individual GETs.
Also added capability to tell the client what TLS version to use.
Sorry these are in the same PR

protonuke: timing & TLS

---

src/minimega/cc.go
src/minimega/cc_cli.go
src/minimega/container.go
src/minimega/kvm.go
src/minimega/misc.go
src/minimega/misc_test.go
src/minimega/vm.go
src/minimega/vm_cli.go
src/ron/command.go
src/ron/ron.go
src/ron/server.go
tests/cc_filter
tests/cc_filter.want

Summary:
* Add `cc filter tag=`
* Fix crash caused by implicit filtering
* Fix race with VM tags
* Add better filtering for namespace-specific cc commands/responses.
Closes #488.

ron/minimega: cc++

---

src/minimega/command_meshage.go
src/minimega/meshage.go

Fixes #504. Set the default timeout to 0 which implies no timeout. Users
can set a timeout using `mesh timeout`, if needed.

minimega: remove meshage timeout.

---

doc/content/articles/usage.article
misc/daemon/minimega.init
src/minimega/command_meshage.go

Update docs with renaming of `namespace` flag to `context`. Updated
daemon script with new flag.
Users should update their envs to rename $MM_NAMESPACE to $MM_CONTEXT.
Closes #497.

doc/misc/minimega: s/namespace/context for meshage.

---

doc/content/developer/namespaces.article

Initial cut of developer docs for namespaces. Updates #470.
@djfritz: this is everything I can think of so far, any thoughts on completeness? Maybe will have some more ideas next week.
This ticket assumes that all the in-flight PRs get merged (although it's not too far off the `master` implementation).

doc: add namespace article for developers.

---

src/minimega/container.go
src/minimega/vmconfig.go
src/minimega/vmconfig_cli.go

Fixes #507. Return an error if the filesystem is not set for containers.
Tweak `vm config init` so that it uses the `vmConfigSlice` helper (specifically, needed `PrintCLI`). Fixes an issue when trying to launch containers with namespaces.

minimega: container tweaks

---

src/minicli/builtins.go
tests/builtins
tests/builtins.want

Now includes four patterns for filters:
```
.filter host=ccc1 vm info
.filter host!=ccc1 vm info
.filter host~ccc vm info
.filter host!~ccc vm info
```
The latter two being substring matching. Added implicit substring matching for fields that appear to be JSON objects (e.g. `tags` in `vm info`) -- we already had this for fields that appear to be lists. Also made the code a lot more readable.

minicli: improved .filter builtin

---

src/minicli/minicli_test.go

Update function type to match update minicli.CLIFunc type.
Fixes #516.

minicli: fix compile error in test

---

src/iomeshage/handler.go

Need to hold TIDLock before touching TIDs.

iomeshage: fix concurrent map access

---

src/iomeshage/handler.go
src/iomeshage/iomeshage.go

Release TIDLock before sending on channel. Move TIDLock into IOMeshage
struct and rename to tidLock so that it is no longer exported.

iomeshage: fix #519

---

src/minicli/builtins.go
src/minicli/minicli.go
tests/builtins
tests/builtins.want

Works similar to bash aliases. Updated minitests. Fixes #528.

minicli: add .alias and .unalias builtins

---

src/minimega/vm.go
src/minimega/vm_cli.go
src/minimega/vmlist.go

Fewer columns than `vm info` but with the same meanings. Fixes #510.
@floren @djfritz: these seemed like a reasonable subset of the columns, thoughts?

minimega: add `vm summary`

---

src/minimega/stats.go
src/minimega/vmlist.go

Report the number of vms in the active namespace and across namespaces
for the host. Fixes #539.

minimega: add vms column to hosts API

---

src/meshage/client.go
src/meshage/message.go
src/meshage/node.go

Control access to Node.clients via Node.clientLock. Fixes #525.
Going to test this today.

meshage: fix data races

---

src/bridge/bridges.go
src/bridge/container.go
src/bridge/ip.go
src/bridge/tap.go
src/minimega/container.go

Created a local err in `Container.launch` when calling `bridges.Get`. If
this failed, we wouldn't register a MAC with the bridge so when we tried
to unregister it, minimega panicked. Move networking code to a separate
function so it's easier to return an error if there's a problem rather
than break out of the loop. Fixed some potential issues in the bridge
code when creating and destroying a bridge.

bridge/minimega: fix #540

---

doc/content/developer/locking.article
src/minimega/capture.go
src/minimega/capture_cli.go

This PR has two features:
* Added article describing locking in minimega.
* Remove `captureLock` which I realized was unneeded why writing article.

doc/minimega: locking docs, remove unneeded lock

---

src/protonuke/smtp.go

Have `smtpServer()` report when it accepts a new connection.
Fixes #579

Send over `smtpReportChan` on new mail.

---

src/minimega/vm.go

Use printVLAN in `vm info` so that we show the network names.

minimega: printVLAN in `vm info`

---

doc/content/articles/tutorials/cc.article
src/miniccc/main.go
src/minimega/cc.go
src/minimega/vmlist.go
src/minimega/vnc.go
src/ron/client.go
src/ron/ron.go
src/ron/server.go

... via updating tags from miniccc
This adds a -tag flag to miniccc which allows adding a tag to that VM's tag map. A few internal changes had to be made to support this. Tags are sent on-demand as well, so this can be used for fast information passing. 
Don't merge until after #564 is fixed and this gets updated against it.
@jcrussell

let vms control their destiny

---

src/protonuke/hosts.go
src/protonuke/http.go

You can't do an Atoi on a hex address.
If you set an HTTP timeout of 30 seconds, it'll give up on a transfer after 30 seconds. I fixed that.

protonuke: timeouts and ipv6

---

src/minimega/kvm.go
src/minimega/vmlist.go

If we have lots of containers and call `vm kill all` then we will likely
timeout when receiving the ACKs. Removed the timeout so that we'll
always wait until everything has ACK'ed.
There's probably a race condition if the VM quits while we are trying to
kill it.

minimega: remove kill timeout a.k.a. I'll never let go

---

src/minimega/container.go
src/minimega/kvm.go
src/minimega/vm.go
src/minimega/vmlist.go

Copy VMs before shoving them into the data field to prevent a race
condition on VM tags.

minimega: gotta copy em' all

---

src/minirouter/ip.go
src/minirouter/misc.go

We currently get interface names by an index and allow ioutil.ReadDir to sort names for us. This works with fewer than 10 interfaces (as it was tested). When you get greater than 10, you end up with sorted names like:
eth0
eth1
eth10
eth11
eth2
eth3...
This PR adds a sort interface to sort on the integer part of the string instead.
@jcrussell

minirouter: fix interface sorting in findEth()

---

src/ipmac/ipmac.go

If a MAC isn't registered, we shouldn't panic.
Fixes #596.

ipmac: check for mac before closing

---

src/minimega/container.go
src/minimega/vm.go
src/minimega/vm_cli.go

KVM VMs aren't the only type that may be able to do screenshots. Instead,
we can make Screenshot part of all VM types, and just have containers
return an error if you call it.
@djfritz @jcrussell

minimega: screenshots are now integral to vms

---

doc/content/articles/installing.article
doc/content/articles/vmtypes.article

Give concrete example of how to turn on the memory cgroup for Debian.

docs: add more cgroup setup info to documents

---

src/goreadline/goreadline.go

Although it's not needed on Debian, some distros (e.g. Slackware) appear to
need this. Tested that it still compiles on Debian.

minimega: add -ltermcap to goreadline LDFLAGS

---

src/miniccc/main.go
src/ron/server.go
src/ron/uuid_windows.go

- Don't create the domain socket on windows clients... because we can't
- Don't unmangle the UUID on non-windows xp clients
@jcrussell @floren @mwisely

miniccc/ron: two updates for windows clients

---

src/vmbetter/external.go
src/vmbetter/targets.go

because syslinux and ext4 don't get along well in all situations. For the time being, ext3 should be safe in all cases.

Change mkfs.ext4 to mkfs.ext3

---

src/minimega/vm.go
src/minimega/vm_cli.go
tests/vm_qos.want

Fixes #606. Qos info is now printed using the network index and updated the qos tests to reflect this change.

qos info now prints network indexes

---

src/minimega/namespace_cli.go

So that we can clear all the hosts.

minimega: support wildcard in `nsmod del-host`

---

src/minimega/namespace_cli.go

So that we can add all the mesh peers.

minimega: support wildcard in `nsmod add-host`

---

src/minimega/container.go
src/minimega/kvm.go

Need to copy the BaseConfig which contains the VM's tags in the VM Copy
functions. Fixes #653. Tested with 20k curls to localhost:9001/vms/.
@floren

minimega: fix concurrent map access

---

src/minicli/output.go
src/minimega/namespace_cli.go
src/ranges/ranges.go
src/ranges/trie.go
src/ranges/trie_test.go

Moving `compressHosts` function from minicli to ranges as `UnsplitList`.
This function was previously used by minicli's output formatter to
condense a list of hostnames into a pretty range. We now use this when
printing the hosts that belong to a namespace.

minimega/minicli/ranges: moving code

---

src/minimega/container.go

Check that CGROUP_ROOT exists before trying to unmount it. Removes:
ERROR container.go:1507: cgroup_root unmount: no such file or directory
Fixes #633.

minimega: check exists before unmounting

---

src/protonuke/flag.go
src/protonuke/http.go
src/protonuke/protonuke.go

Parse the file size as a custom flag type so that we can have suffixes
like B/KB/MB. Default is still MB but now we can specify images smaller
than 1MB using the B or KB suffix.

protonuke: smarter file size parsing

---

src/gonetflow/gonetflow.go
src/nfcat/main.go

Adding tool `nfcat` that reads the binary netflow format written by minimega.
Required small changes to gonetflow which haven't been tested yet... probably fine?

nfcat: tool to read binary netflow

---

src/minimega/router.go
src/minimega/router_cli.go
src/minirouter/dnsmasq.go

Add option to set upstream dns server. Useful when creating a hierarchy.

minimega/minirouter: add upstream dns

---

src/iomeshage/iomeshage.go

Delete the contents but not `iom.base` when called via `file delete /`.
Restrict paths to within the `iom.base` directory (e.g. not `file delete ../../../../`).
Fixes #574

iomeshage: don't delete the root

---

src/iomeshage/iomeshage.go

Return a deep copy of the transfer from IOMeshage.Status. This
eliminates a warning from the race detector (and eliminates the
possibilty of someone tinkering with the transfers struct).
Fixes #652.

iomeshage: create deep copy for IOMeshage.Status

---

src/minimega/vm.go
src/minimega/vmlist.go

Call to ron.Server.UnregisterVM while holding VM's lock could result in
a deadlock. Moved call to unregister VM to VMs, mirroring how RegisterVM
is called.

minimega: fix deadlock with flushing VMs

---

src/minicli/output.go
src/minicli/output_test.go

Displays IDs in the correct order (e.g. `cc commands`). Fixes #538.
Includes unit tests.

minicli: if values are int, sort using int compare

---

src/minicli/input.go
src/minicli/minicli.go
src/minicli/minicli_test.go
src/minimega/vmconfig_cli.go

Handle escaped quotes and empty quoted strings:
```
minimega$ vm config tag foo "foo bar"
minimega$ vm config tag
{"foo":"foo bar"}
minimega$ vm config tag foo "foo \"bar\""
minimega$ vm config tag
{"foo":"foo \"bar\""}
minimega$ vm config tag foo ""
minimega$ vm config tag
{"foo":""}
```

minicli: improvements for handling quoting

---

src/minilog/minilog.go
src/minilog/minilog_linux.go

#690 breaks windows builds of protonuke, miniccc, etc. This moves the syslog helper in minilog to a linux specific source file. 
@jcrussell

minilog: add linux specific build files for syslog helper

---

doc/content/articles/vmtypes.article
misc/vmbetter_configs/ccc_host_ovs_overlay/init
src/minimega/container.go
src/minimega/main.go

Continue to work around systemd. This time by changing our non-systemd cgroup behavior to simply match the default systemd cgroup hierarchy on ubuntu 16.04.
@jcrussell

cgroups, systemdont

---

src/minimega/container.go
src/minimega/kvm.go
src/minimega/vm.go

The race detector detects a possible race with the copied VM mutex. In
order to avoid this entirely, don't copy the mutex.
Fixes #650

minimega: never copy VM mutex

---

src/minilog/logger.go
src/minilog/minilog.go
src/minilog/minilog_test.go

Add an RWMutex to minilog to synchronize access to global state. If you were adding a logger while something was logging, a concurrent map access could cause a panic.
This adds some overhead but it seems pretty minimal (from BenchmarkLogging):
Without lock: 77560 ns/op, total time: 3.022s
With lock: 78526 ns/op, total time: 3.052s
Fixes #515

minilog: remove data race

---

src/minimega/cc.go

Display tags in `cc commands`:
minimega$ cc filter foo=bar
minimega$ cc filter
UUID | hostname | arch | OS | IP | MAC | Tags
|          |      |    |    |     | {"foo":"bar"}
minimega$ cc exec ls
minimega$ .columns command,filter cc commands
command | filter
[ls]    | foo=bar
Fixes #572.

minimega: add tags to filterString

---

src/minimega/router.go

Store a reference to the VM in the Router struct so that we can get the
VM's namespace/uuid when addressing it for ron commands.
Fixes #629 -- probably. Needs testing.

minimega: add VM to Router struct

---

src/bridge/bridge.go
src/bridge/mirror.go
src/bridge/netflow.go
src/bridge/ovs.go
src/bridge/tunnel.go
src/minimega/external.go

Refactor some of the ovs code and remove the timeout. Refactor how we check versions and increase minimum ovs version to 1.11. Remove "all external dependencies met" message from `check` API.
Need to do some testing before we merge this.

minimega/bridge: refactoring, remove ovs timeout

---

src/minimega/namespace.go

Make standalone minimega a little simpler -- add localhost to namespace
automatically.

minimega: if there are no peers, add localhost

---

misc/web/js/glue.js
misc/web/js/graph.js
misc/web/terminal.html
misc/web/vnc_auto.html
src/minimega/tunnel.go
src/minimega/web.go

"Do the right thing" based on the VM type rather than using specific
URLs. Makes it really nice to connect to either the VNC or terminal for
a VM by name. For example:
```
web
vm config filesystem /data/minimega/containerfs
vm launch container 1
vm launch kvm 1
vm start all
```
The URLS to connect are then:
http://localhost:9001/connect/vm-0
http://localhost:9001/connect/vm-1

minimega/web: merge vnc/terminal URLs

---

src/minimega/cli.go

Add preprocessor for $ vars. For example:
```
minimega$ echo $SHELL
/bin/bash
minimega$ echo $SHEL
Error: undefined: $SHEL
```
Fixes #713.

minimega: add env preprocessor

---

src/bridge/ovs.go
src/minimega/external.go

Try and run `ovs-vsctl show` in the external check to test if ovs is
running or not. Tired of trying to start VMs and having things blow up
on my laptop that doesn't start ovs on boot.

minimega/bridge: check to see if ovs is running

---

src/bridge/bridges.go
src/bridge/ipmac.go

bridge.Destroy would block forever if there are running VMs since the
snooper was holding a lock and blocking on reading packets. Set a
timeout and loop if we timeout so that we can close the pcap handle.
Fixes #723

bridge: fix deadlock in bridge.Destroy

---

doc/content/articles/cluster.article
doc/content/articles/installing.article

installing.article no longer contains information about setting up the network. Instead,
the new file cluster.article describes in more detail how you can set up a cluster
to run minimega.

documentation: create cluster.article

---

src/gopcap/gopcap.go
src/minicli/handler.go
src/minicli/minicli.go
src/minimega/capture.go
src/minimega/capture_cli.go
src/minimega/cli.go
src/minimega/kvm.go
src/minimega/main.go
src/minimega/vm.go
tests/capture
tests/capture.want
tests/epilog

Made the capture API more namespace aware, still not fully though. Fixed
a bug in `clear capture` where it was only stopping the first capture.
Passes local test, need to try in a multiple node experiment.
Also: fix segfault in gopcap and minor improvement to minicli.
Fixes #707
@glattercj -- do you want to test this?

minimega: make capture more namespace aware

---

src/minimega/cli.go

For example:
```
minimega$ vm config filesystem $minirouterfs
INFO cli.go:473: cliPreprocess: [filesystem] $minirouterfs -> /data/minimega/minirouterfs
minimega$ vm config filesystem
/data/minimega/minirouterfs
minimega$ vm config preinit $minirouterfs/preinit
INFO cli.go:473: cliPreprocess: [preinit] $minirouterfs/preinit -> /data/minimega/minirouterfs/preinit
minimega$ vm config preinit
/data/minimega/minirouterfs/preinit
```

minimega: split env variable on space and slash

---

src/minimega/kvm.go
src/minimega/vnc_record.go

Tweak the vnc shim loop so that we disconnect the VNC client when the VM
shuts down. Moved access to vncKBRecording to vncRoute to wrap with lock
to remove race.
@cdshann

minimega: tweak vnc shim loop, remove race

---

src/minimega/vnc.go
src/minimega/vnc_cli.go

Added missing locking in vncClear. vncRecordingLock > vncPlayingLock.
Return standard error rather than custom error when vm not found.

minimega: add locking in vncClear, other tweak

---

src/minimega/router.go

Previously, minimega would only assign one DNS hostname per IP, ignoring all but the
last. minirouter supported more, so a simple modification to minimega makes it work
right.

minimega: multiple dns entries for a single ip with minirouter

---

src/minirouter/bird.go
src/minirouter/misc.go

Bird was choking if you defined static routes, because it used only one
config file. If you defined ipv4 static routes, bird6 would die because
it couldn't parse the v4 routes, and vice versa. This creates /etc/bird6.conf
and makes bird6 use that instead, which has solved the problem in testing.

minirouter: handle v6 static routes better

---

src/minimega/cli.go
src/minimega/iomeshage.go
src/minimega/vmlist.go

Add a new function to the QueuedVMs to fetch all the files that are in
the f_iombase directory which is invoked before the VMs are launched.
This applies to VMs that come in over meshage or are launched locally,
with and without a namespace. Improved the iomHelper to be smarter about
absolute paths and to supress in-flight errors.
Updates #768.

minimega: fix unpreprocessed files

---

src/minimega/capture.go

Avoids a deadlock by closing the capture from a separate goroutine.
Since we destroy the mirror, the capture and the goroutine to close the
capture should complete, eventually.
Fixes #765.

minimega: close capture from separate goroutine

---

src/minimega/vm.go
src/minimega/vm_cli.go

Add optional flag to `vm info` so that you can get a subset of the
fields. A more idiomatic minimega.

minimega: move `vm summary` into `vm info`

---

src/minimega/kvm.go
src/minimega/vmconfig.go
src/minimega/vmconfig_cli.go
tests/vm_config_save.want

Before, `vm config qemu` would only affect the local minimega instance.
Add field to KvmConfig for QemuPath and fallback on `process("kvm")` if
not set.
Fixes #786

minimega: fix `vm config qemu` with namespaces

---

src/minicli/builtins.go
src/minicli/command.go
src/minicli/minicli.go

We weren't passing the history minitest because of a bug in minicli.
Added note to `minicli.Command.Record` to explain why we did things the
way we did.

minicli: fix history recording

---

test.bash

Should have been removed with python bindings, whoops.

test.bash: remove python test

---

src/protonuke/cookie_test/server.go
src/protonuke/http.go
src/protonuke/protonuke.go

Add a new flag to enable cookie jar in http/https clients. Added a test
server that can be used to verify that the cookie jar is working as
intended. Blocking on #817.
Fixes #809.

protonuke: add cookie jar to http/https clients

---

src/minimega/vm.go

minimega: copy missing field

---

src/miniclient/client.go
src/minimega/command_socket.go
src/minimega/main.go
src/minitest/main.go

Downgrade the interface between minimega and miniclient to a string
rather than a compile `minicli.Command`. This is for (at least) two
reasons:
* minimega had to recompile the command anyways since the function
pointer cannot be encoded
* non-minimega clients (e.g. minitest, miniweb) are unable to compile
minimega commands (since they have not registered the same handlers)
Fixes #827

mini*: downgrade miniclient to string

---

src/minicli/handler.go
src/minimega/namespace.go
src/minimega/namespace_cli.go
tests/epilog
tests/namespace
tests/namespace.want

Make it an error to switch to the same namespace as the active namespace. Make it an error to "clear namespace" when no namespace is active. Support "clear namespace all" to delete all namespaces. Change miniccc to support suggestions on optional items. Add suggestions for namespace names to namespace API.

minimega/miniccc: namespace API improvements

---

src/minimega/container.go

Enforces the VCPUs set via `vm config vcpus`.
Fixes #837.

minimega: add container quotas

---

src/minimega/bridge.go
src/minimega/container.go
src/minimega/kvm.go
src/minimega/main.go
src/minimega/misc.go
src/minimega/vm.go

Call log.Fatal instead of teardown if we aren't able to write data.
Renamed function to mustWrite.
Fixes #684

minimega: fix writeOrDie deadlock

---

CONTRIBUTORS
misc/web/vnc_auto.html

Previously it was set to just the hostname of the server that served the html file. It makes more sense for it to be the name of the VM.

Changed VNC page title to VM name.

---

src/minidoc/dir.go

Can now clone "http://minimega.org/minimega.git". Good find @mkunz7!
Fixes #487.

minidoc: add vanity URL

---

src/passwordify/main.go

Making the build fail on un-gofmt'd code, in my opinion, makes us
even worse than Python: rather than fail due to significant whitespace,
we fail due to insignificant whitespace.
#892

gofmt passwordify

---

src/bridge/bridge.go
src/bridge/doc.go
src/bridge/ipmac.go
src/bridge/qos.go
src/bridge/tap.go
src/minimega/qos_cli.go
src/minimega/vm.go
tests/vm_config_net.want
tests/vm_qos.want

Use tbf instead of netem for rate limiting since netem didn't seem to
behave correctly between VMs on different hosts. Unfortunately, this
means that rate and loss/delay are mutually exclusive now. Documented
this and made a few cleanups. Updated tests.
Tested between two containers on different hosts.

bridge: ``fix'' qos code

---

misc/vmbetter_configs/ccc_host_ovs_overlay/init
misc/vmbetter_configs/miniccc_virtio_overlay/init
misc/vmbetter_configs/minirouter_overlay/init

Use virtio port names from sys to populate /dev/virtio-ports and use
that instead for miniccc. More robust than using hardcoded vport1p1.

misc: update init for virtio

---

src/minicli/builtins.go
src/minimega/cli.go

Added .env to print/update/unset env variables. Use os.ExpandEnv instead
of custom code to expand env variables -- now support $var or ${var}.
Closes #909

minimega/minicli: improved env support

---

misc/vmbetter_configs/ccc_host_ovs_overlay/init

The only node that uses bonding isn't fully wired so there's no point to
bonding the interfaces (and the switch isn't configured for LACP on that
interface).

misc: disable ovs bonding

---

.travis.yml
doc/content/articles/installing.article
misc/web/js/glue.js
misc/web/templates/vms.tmpl
src/miniweb/handlers.go
src/miniweb/main.go
src/miniweb/tabular.go
src/miniweb/vms.go

Use sort.Slice to clean up some code. Made vmInfo cleaner and use in the
vms handler. Set record false so we don't clutter the history.

miniweb: clean up code, set record false, add `vm top` view

---

src/minimega/kvm.go

`if` defaults to `ide` and `index` is automatically incremented
according to the qemu docs so we can emit both. This fixes #926 which
was a result of using a hardcoded index.

minimega: fix cdrom with multiple disks

---

src/minimega/router.go
src/minimega/router_cli.go
src/minirouter/route.go

Add API to set the default route for minirouter. Fixes #936.

minimega/minirouter: add default route API

---

doc/content/articles/router.article
misc/vmbetter_configs/minirouter_overlay/init

Add IP forwarding by default. Remove -qcow from vmbetter instructions.
Fixes #917

doc,misc: update minirouter

---

src/minimega/namespace.go
tests/distributed/vm_names
tests/distributed/vm_names.want

Ensure that `vm launch ... N` results in VMs with unique names. Fixes
regression from 550f4b. Thanks to `git log -S` for helping me find when
it broke.
Fixes #988.

minimega: ensure unique names for unspecified vms

---

src/vmbetter/debootstrap.go
src/vmbetter/main.go

Like to be able to specify the archive components to use (e.g. main, restricted, universe and/or multiverse for an ubuntu mirror) on the vmbetter cli.

vmbetter: add 'components' option to cli

---

src/igor/main.go

err will be EACCES or EAGAIN if lock is already held. Prevents race when
multiple instances are running at the same time.
@csymonds

igor: check sycall.Flock err

---

src/igor/cobbler.go
src/igor/main.go
src/igor/sub.go

Parse `cobbler profile list` into a map and check whether the requested
profile is in the map. This prevents a substring of a valid profile name
from being used.

igor: stricter usage of `cobbler profile list`

---

src/minimega/vm.go
src/minimega/vm_cli.go
tests/vm_net
tests/vm_net.want

`vm net` now supports the same vm target syntax as `vm start`. Made
bridge an optional parameter that defaults to `mega_bridge`. Fixes bug
where `vm net` used wrapSimpleCLI instead of wrapVMTargetCLI -- before
it wouldn't work across a namespace.
Fixes #994.
We should merge this before 2.4 since it includes a bug fix (and a
useful feature). Most of the additions are tests.

minimega: improve vm net

---

src/minimega/cli.go
src/minimega/command_meshage.go
src/minimega/namespace_cli.go

Make sure preprocess gets set on all subcommands. Set record=false on namespace subcommands.

minimega: fix bugs with minicli flags

---

src/minicli/command.go
src/minicli/handler.go
src/minicli/minicli.go
src/minicli/util.go
src/minimega/plumber.go

Rewrite minicli.Help to be easier to understand and print help for
commands like `vnc record`. Shortened the short help for plumb so that
the line does not wrap.
Fixes #1022.

minicli/minimega: rewrite minicli.Help

---

src/minimega/misc.go

Return an error if the VLAN is empty instead of hitting `log.Fatal`.
Fixes #1031.
@mkunz7

minimega: fix empty VLAN bug

---

src/protonuke/flag.go
src/protonuke/http.go

Make the image size a query parameter:
```
http://10.0.0.1/image.png?size=1MB
http://10.0.0.1/image.png?size=16MB
```
If the size is not specified, it will use the size from the CLI flag. The image is generated on the first query for the given size and stored in memory for future requests. This could cause OOM issues if people query for many different image sizes. 
Set the `Server` HTTP header to `protonuke/$VERSON` where `$VERSION` is `version.Revision`. This makes it easier to figure out what version of protonuke you're querying.

protonuke: parameter for image size, header for version

---

src/rond/client.go
src/rond/handlers.go
src/rond/main.go

Add a `-e` flag to run a command against a running instance of `rond`.
Add `checkpoint` to wait for all clients to complete all previous commands.
Add `clear commands` to clear commands stored by `ron`.

rond: add `-e` flag, `checkpoint`, and `clear commands`

---

src/igor/show.go
src/igor/sub.go

Uncomment the network isolation code. Will only be used if enabled in
config. Change nmap args so that `igor show` works when most of the
cluster is off.

igor: minor tweaks

---

src/igor/main.go
src/igor/notify.go

json to gob cuts down the time to load from 20s to <1s.
Add `igor notify`. Only runnable by root. Notifies user of upcoming and expiring reservations.
Fixes #958.

igor: send emails, replace json with gob

---

src/igor/power.go
src/igor/schedule.go
src/igor/sub.go

Adding in a bounds check to prevent a panic when user requests a node out of range.

igor: Adding Bounds Check

---

src/minimega/namespace.go
src/minimega/vmconfig.go
src/minimega/vmconfig_cli.go

Reprocess the original `vm config net` so that we generate new tap
names, if unspecified. Clear `vm config uuid` because we can't boot VMs
with the same UUID.
Updates #1072.
@mkunz7

minimega: fix `vm config clone`

---

src/minimega/kvm.go

minimega uses `kvm` by default which typically runs `qemu-system-x86_64`
with `-enable-kvm` so it is redundant to include the flag. This makes it
simpler to run different architectures since you can change the qemu
path and don't need to add a qemu override to remove the `-enable-kvm`
flag.
Fixes #1076

minimega: nix second -enable-kvm

---

src/minimega/kvm.go
src/minimega/vm_cli.go
src/qmp/qmp.go

Allow the user to give a USB disk a serial number. Implemented this to track USB devices across a virtual enterprise.

Usb serial number

---

src/minimega/vnc_playback.go

Fix leak of VNC connections by closing vnc playbacks when it finishes
playing the top-level file.

minimega: properly close vnc playbacks

---

doc/template/action.tmpl
src/present/parse.go

Not having nested bullets in present is terrible and the golang authors have decided not to add support. It's a simple patch but maybe we want to keep this as a .patch and have the build scripts apply it instead of modifying vendorized code...
@jcrussell

minidoc/present: add nested bullet support with "-- "

---

src/minimega/namespace.go
tests/distributed/vm_names.want

Each namespace has its own counter and names don't have to be unique
across namespaces so remove the namespace from the default vm name.

minimega: remove namespace from default vm name

---

misc/vmbetter_configs/carnac_host.conf
misc/vmbetter_configs/ccc_host.conf
misc/vmbetter_configs/default_amd64.conf
misc/vmbetter_configs/host.conf
misc/vmbetter_configs/miniccc.conf
misc/vmbetter_configs/miniccc_container.conf
misc/vmbetter_configs/miniception.conf
misc/vmbetter_configs/minirouter.conf
misc/vmbetter_configs/minirouter_container.conf
src/vmconfig/vmconfig.go

vmconfig had magic to find parent config files based on the root config.
Improve the magic so that instead of looking in the dir of the root
config, vmconfig looks in the dir of the current config.
Change the overlay directories to be a path relative to the config file
so that we can run vmbetter from anywhere.
Update all the configs to use this paradigm.

vmconfig: more magic

---

src/minimega/container.go
src/minimega/vm.go
src/minimega/vm_cli.go

Containers only have interfaces when they are running so check the state
before trying to interact with OVS. Otherwise, update the NetConfig and
return.

minimega: add container-specific network functions

---

src/minimega/vnc_cli.go

Use `wrapVMTargetCLI` to make `vnc` work better with namespaces.

minimega: fix vnc with namespaces

---

src/minimega/misc_cli.go

Add helpful `<filename>:<line>` to read errors.
Fixes #977

minimega: prepend line number for read error

---

src/minimega/misc_cli.go

To make sure that there is only one response from `clear all`.
Fixes #1038

minimega: use consume in `clear all`

---

src/miniccc/commands.go

Check the files dir in addition to $PATH. Simplifies `cc exec`:
cc send foo
cc exec foo
Instead of:
cc send foo
cc exec /tmp/miniccc/files/foo
Fixes #1040

miniccc: look in files dir for executables

---

src/minimega/misc_cli.go
tests/read_namespace
tests/read_namespace.want

Prepend the original namespace to read commands so that if another
script/user changes the namespace, we still run the commands in the
intended namespace.
Fixes #968

minimega: prepend namespace to read commands

---

src/minimega/cli.go
src/minimega/external.go

Fetches and untars tarballs via meshage. Current only untars if there is
a single top-level directory. It untars to the same directory that
contains the tarball... we probably don't want that when the tarball is
in the iomBase. Maybe it would be better to always untar to
/tmp/minimega/???.
Thoughts? @djfritz

minimega: add `tar:` prefix

---

src/igor/extend.go

Check for conflicts should only check for count 1 since it tests each
index.

igor: fix bug in extend

---

src/igor/show.go

Padding out display of shorter res names with spaces to match the length of longer resnames because golang tabwriter cannot align correctly.

igor: Improved alignment on show. 

---

src/igor/config.go
src/igor/extend.go
src/igor/schedule.go
src/igor/schedule_test.go
src/igor/sub.go

Time limits are now based on the number of nodes (well log of the number
of nodes). Extensions can be made as long as the reservation is near the
end (config-defined) and can be performed indefinitely.

igor: change time limits

---

src/minicli/command.go
src/minicli/minicli.go
src/minimega/misc_cli.go

Fix bug where we would return already in namespace errors if there were
comments in the read file.

minicli/minimega: fix read when there are comments

---

src/miniccc/client.go
src/miniccc/main.go

So that we can run -h without a uuid.

miniccc: move code out of init

---

src/igor/main.go
src/igor/show.go

Adding an option to the show command to allow sorting by owner name to make it easier to find reservations by owner

igor: show - sort by owner

---

misc/vmbetter_configs/carnac_host.conf
misc/vmbetter_configs/carnac_host_overlay/init

Create RAID0 from sdb/sdc and use for /scratch. Leave sda floating so
that users can mount where needed.

misc: support new drives in carnac

---

src/miniccc/main.go
src/minimega/container.go
src/minimega/kvm.go
src/minimega/namespace.go
src/minimega/vm.go
src/minimega/vm_cli.go
src/minimega/vms.go
src/ron/server.go
src/ron/tunnel.go
tests/cc_reconnect
tests/cc_reconnect.want

Add synchronization bytes to hopefully allow ron and miniccc to reconnect. Write the magic bytes in both directions to flush both sides.
Add redial to the things we do when we start a VM.

ron/miniccc/minimega: improving reconnect

---

src/igor/config.go
src/igor/notify.go

Added a new field for the config file called expirationleadtime. It allows admins to set how much lead time in hours to notify users about pending reservation expiration . if no value is specified a default lead time of 24 hours is in effect

Igor notify conf

---

src/miniclient/client.go

Too many minimega -e's can cause minimega's listen queue to fill up and
start rejecting new miniclients. Add redial/backoff when we detect a
temporary error.

miniclient: add redial on temporary error

---

src/bridge/mirror.go
src/minimega/bridge.go
src/minimega/bridge_cli.go
src/minimega/capture.go
src/minimega/vm.go
tests/capture.want
tests/distributed/tap_mirror_vm
tests/distributed/tap_mirror_vm.want
tests/tap_mirror_vm
tests/tap_mirror_vm.want

Allows you to specify tap mirrors by VM names and interface indices.
Needs testing.
Updates #1217

minimega: add vm->vm tap mirror

---

src/minimega/kvm.go
src/minimega/namespace.go
src/minimega/scheduler.go
src/minimega/scheduler_test.go
src/minimega/vmconfig.go
src/minimega/vmconfiger_cli.go
src/minimega/vms.go
src/vmconfiger/generator.go
tests/distributed/vm_colocate
tests/distributed/vm_colocate.want
tests/distributed/vm_colocate_errors
tests/distributed/vm_colocate_errors.want
tests/distributed/vm_colocate_queueing
tests/distributed/vm_colocate_queueing.want
tests/distributed/vm_colocated_errors
tests/vm_config_save.want

Allow users to schedule VMs on the same host via `vm config colocate`.
* Supports chaining -- a with b, b with c, c with d.
* Cannot specify `vm config schedule` with `vm config colocate` to simplify the code.
* Can specify `vm config schedule` on "root VM" and then colocate VMs with it.
* Minor fix to `vmconfiger`.
Has some unit testing, need to do some more testing.

minimega: add `vm config colocate`

---

misc/vmbetter_configs/host_overlay/lib/x86_64-linux-gnu/libreadline.so.6

minimega no longer needs libreadline so trim this from overlay.

misc: trim libreadline overlay

---

doc/content/static/article.css
doc/template/article.tmpl
doc/template/dir.tmpl
doc/template/layout.tmpl
src/minidoc/dir.go

Tweak templates so that we embed the article within the standard layout
template. Muck around with CSS a bit since pages and articles conflict.
Fixes #1219

minidoc: show header/sidebar in articles

---

doc/content/articles/namespaces.article
src/minimega/meshage.go
src/minimega/namespace.go
src/minimega/namespace_cli.go
src/minimega/vm_cli.go
tests/distributed/ns_schedule
tests/distributed/ns_schedule.want

Dry run of the scheduler that prints out VM placement. User can then edit the placement as needed before running it. Rename `ns schedules` to `ns schedule status`. Fix bug in schedule status where launched VMs weren't being counted properly.
Fixes #1229.

minimega: add dry-run to scheduler

---

src/minimega/container.go
src/minimega/vms.go

If a container filesystem is busy, retry a few times to see if we can
unmount it. Add VM ID to clogged error.
Needs testing.

minimega: retry unmount

---

src/igor/.gitignore
src/igor/reservation.go
src/igor/reservation_test.go
src/igor/schedule.go
src/igor/schedule_test.go

Two issues: reservations that spanned other reservations and using the
start time of the first host in a block rather than the max.

igor: fix corner cases in scheduler

---

src/minimega/main.go

If there's only one argument, pass it directly as the command.
Tested with:
minimega -e echo 'hello, world'
minimega -e "echo 'hello, world'"
@mkunz7

minimega: fix #1279

---

src/minimega/vm_cli.go

Try to unmarshal the raw argument to filter invalid JSON objects which
could bork our qmp connection.
Fixes #1259

minimega: vm qmp sanity check

---

src/minimega/kvm.go
src/minimega/vmconfiger_cli.go
tests/vm_config_save.want

Users can now specify a list of named virtio ports or a number of virtio
ports to automatically generate names for (old behavior).
Fixes #1293.
TODO:

minimega: support named virtio ports

---

src/minimega/minimega.go
src/minimega/namespace.go
src/minimega/namespace_cli.go

Make sure namespace and VM names are sanitized since we create
directories and argument strings based on them.
Fixes #1288.

minimega: name sanitization

---

src/igor/show.go

Add option for JSON encoded output to `igor show`
This helps igor web get a list of reservations without worrying about file locking.  Let igor handle that.

igor: Add -json flag to 'igor show'

---

.gitignore
src/pyapigen/template.go

Use readline in order to improve performance. Drop timeout since we can't use readline in non-blocking mode.

pyapigen: tweak template

---

doc/content/articles/miniweb.article
src/miniweb/handlers.go
src/miniweb/main.go

Specify the path to minimega with -console to enable.
Fixes #1301

miniweb: change -console to string

---

misc/vmbetter_configs/minimal_ubuntu.conf
src/vmbetter/main.go
src/vmbetter/targets.go

Change -qcow to -disk and add the option to specify the disk format
(currently allows qcow, qcow2, raw, and vmdk). Rename -qcowsize to
-size. Change the default mbr location so that it matches debian.
Needs more testing.

vmbetter: even better

---

src/qemu/qemu.go

Some versions of qemu have a header and others don't so check for the
specific header.

qemu: don't ignore first line in cpu list

---

src/pyapigen/template.go

Convert Header/Tabular to list of dicts. For example:
```python
import minimega
mm = minimega.connect()
for r in mm.vm_info():
print(minimega.as_dict(r))
```

pyapigen: add as_dict method

---

src/minimega/vms.go

Perhaps a better solution to the slow container Flush() than #1350 
@jcrussell this is only tested against 10 containers - can we subject this to the minitest suite before merging?

minimega: fix parallel flush

---

misc/vmbetter_configs/carnac_host_overlay/init
misc/vmbetter_configs/ccc_host_overlay/init

/dev/fd fixes a bash issue. Mirror mtab changes from carnac to ccc.

misc: add symlinks

---

src/minicli/minicli.go
src/miniclient/client.go
src/minimega/cli.go
src/minimega/command_socket.go

Fix double expansion and only replace the first full word on a line.
Fixes #1360

various: fix .alias

---

misc/web/templates/vms.tmpl

Forcing the href update before reload as the order of operations is otherwise not guaranteed.
This resolves issue #1306

miniweb: top/info view links fix

---

src/igor/edit.go
src/igor/reservations.go
src/igor/sub.go
src/igor/util.go

Allows users to specify which VLAN they'd like a reservation to connect to. The value of `-vlan` can be:
- the name of another reservation (`string`)
- The specified reservation must be writable by the current user
-  The new reservation uses the same VLAN as the existing one
-  a VLAN ID (`int`)
- ... As long as the specified VLAN ID is not in use by any other reservation, or the VLAN ID is used by at least one existing reservation that is writable for the current user.
- The VLAN ID must be in the range specified by igor's config
If `-vlan` is not provided, igor determines a VLAN ID as usual.
`-vlan` can be specified for `sub` and `edit`

Add -vlan flag to sub and edit

---

src/bridge/container.go
src/bridge/ip.go
src/bridge/process.go

On newer distros, `ip link add` actually respects the iface name given within the container netns now, whereas it didn't before and just gave the vethX as expected.

Fix #1373 broken containers on newer distros.

---

src/apigen/apigen.go

See summary, this also has the benefit of alphabetically sorting the handlers in the output, making searching through the API article a little simpler.
fixes #1375

apigen: sort and collapse handlers based on SharedPrefix

---

src/igor/reservations.go

Fixes an issue where deleting future reservations clobbers network settings for active reservations.

igor: Don't uninstall / clear network settings when deleting future reservation

---

src/igor/reservations.go

Fixes an issue where the network is not cleared when a reservation expires.
@csymonds

igor: Allow uninstall/clear for expired reservations

---

src/igor/stats_test.go

The stats test was failing (twice a year, it would seem) due to time changes affecting test outcome. This PR fixes that issue.

igor: Fix for the igor stats test to avoid DST issues

---

src/igor/power.go

We were dropping the error that comes back from doPower without logging. I suspect this is because any errors that may have come back from the external run of the executed power command would be handled and logged by external.go. However, out of an abundance of caution, I'm logging those errors and noting where we log upstream.

igor: add detail to log

---

src/minimega/namespace.go
src/minimega/vm_cli.go
src/minimega/vms.go
tests/vm_lifecycle
tests/vm_lifecycle.want

- Changed 'all' VM flush method to 'FlushAll()'.
- Created new 'Flush()' method that uses the 'Apply' method to flush a specified target.
- Updated help strings to reflect enhancement.
- Backwards compatible with old `vm flush` behavior
Resolves https://github.com/sandia-minimega/minimega/issues/1392

minimega: specify `flush` target

---

misc/appengine/update.bash

Modified the update script to remove existing update files which will cause the minimega build to fail when the update is run. 
Also included automation for pulling in the google cloud sdk. Tested and worked locally, but was not written with other dev environments in mind and could fail. For example, the google cloud sdk being pulled in is 64-bit x86.
After running this, I have confirmed that the API Documentation link on minimega.org has been restored. This resolves issue #1420

appengine: restore api documentation on minimega.org

---

src/minimega/namespace_cli.go

This prohibits loopback addresses from being used as endpoints in bridges in cliNamespaceBridge in minimega.namespace_cli.go.

minimega.namespace_cli: don't use loopback addresses for GRE tunnels

---

src/igor/config.go
src/igor/config_test.go
src/igor/extend.go

Clarifying logs for extend when duration exceeds limits. Before, the message indicated that the user request more time than specified in their command because we were adding it to the time remaining in their reservation.
Now, we specify that the requested time, plus the time remaining, is what exceeds the limit.

igor: extend clarification

---

src/minimega/disk.go

If you run `qemu-img info` in the same directory as the image your passing to it, then the `(actual path: ...)` stuff isn't included in the output. However, if you run `qemu-img info` from a different directory, or you pass the absolute path of the image to `qemu-img info`, then the `(actual path: ...)` stuff is present. Minimega always passes the full path of a disk image to `qemu-img info`.
As an aside, I'm not sure if this is new functionality in a more recent version of `qemu-img` (I have the following version of `qemu-utils` installed: `focal-updates,focal-security,now 1:4.2-3ubuntu6.10`).

minimega: use "actual path" from qemu-img for backing image if present

---

src/miniccc/main.go
src/minimega/kvm.go
src/ron/server.go

`miniccc` clients currently fail to reconnect if the `miniccc` process is restarted (for example, when a VM is rebooted). This PR addresses the issue.

miniccc: attempt to reconnect to serial cc on disconnect

---

src/minimega/disk.go

Many times, reading in a large script file will result in an error similar to the following:
```
desired partition 1 not found
```
Debugging this is difficult since no additional details are reported. This PR includes the name of the disk image being operated on.

minimega: include image name partition not found error for disk injections

---

doc/content/articles/namespaces.article
src/minimega/kvm.go
src/minimega/namespace.go
src/minimega/vm_cli.go
src/minimega/vmconfiger_cli.go
src/qmp/qmp.go
tests/ns_snapshot
tests/ns_snapshot.want
tests/vm_snapshot
tests/vm_snapshot.want

Closes #1309 
- Adds disk state save to `ns snapshot` command
- For each VM:
- First the disk state is saved using the `drive-backup` qmp command (__*BLOCKS until finished; later plans to implement goroutine for this*__)
- Next the rest of the VM state is saved using the normal `migrate`
- Addresses issue in #1445 by explicitly pausing all VMs as before proceeding with the snapshot

minimega: Enhance ns snapshot

---

src/minimega/router.go
src/minimega/router_cli.go
src/minimega/router_test.go
src/minirouter/fw.go

Both minimega and minirouter were updated to support configuring
iptables in the minirouter instance using new "router fw" commands.
minirouter was updated to include support for "fw" commands for both
global iptables rules and grouped rules using iptables chains.
minimega was updated to include support for "router <vm> fw" commands
that generate the minirouter "fw" commands in the config script sent to
the minirouter instance via miniccc.
Documentation for minimega's "router" command was also updated to
include details and examples of how to use the new "fw" commands.
closes #1236

Add "router fw" commands to minirouter to add iptables FORWARD rules

---

src/miniccc/commands.go
src/minimega/cc_cli.go
src/ron/command.go

minimega, miniccc, and ron were updated to support executing tcp/udp
connectivity tests directly from miniccc agents.
ron was updated to include a new `ConnTest` command struct that
encapsulates the endpoint to test against, how long to wait, and what
UDP packet to send (if necessary).
miniccc was updated to include a handler for the new `ConnTest` command
that simply tries to dial the endpoint (in the case of TCP), and if
necessary write the UDP packet to the socket (in the case of UDP).
minimega was updated to include support for a new "cc test-conn"
command, as well as adding a "connectivity" column to the "cc commands"
table.
Documentation for minimega's "cc" command was also updated to include
details and examples of how to use the new "test-conn" command.

Support TCP and UDP connectivity testing from miniccc

---

docker/minimega.service
src/meshage/node.go
src/minimega/main.go
src/minimega/meshage.go

In some cases, cluster compute nodes have multiple interfaces and
networks they can communicate with each other over, and one may be
desirable over another for meshage comms. By default, minimega uses
`255.255.255.255` as the broadcast address, and when multiple interfaces
are present, the one acting as the default route is the one used.
This commit adds a new command line option, `-broadcast`, for users to
specify which broadcast IP to use for the mesh. It defaults to
`255.255.255.255`, so this commit should be backwards compatible.

Allow user to specify which broadcast IP to use for meshage

---

src/miniccc/heartbeat.go
src/ron/message.go
src/ron/server.go
src/ron/version.go

This is an attempt to make miniccc somewhat future-proof. Right now, if minimega is updated then miniccc running in existing images will continually fail and reconnect because currently we only start the heartbeat on the server if the commit versions between the server and miniccc match. This is somewhat okay, except for when `cc mount` needs to be used.
By versioning the cc message, we can now accurately determine if older miniccc agents can be used with newer versions of deployed servers.

ron: version the cc message so heartbeats work across revisions

---

cmd/minimega/dnsmasq.go

This commit updates the command line flags for dnsmasq to explicitly
point to a non-existent resolv.conf file rather than letting it use the
default /etc/resolv.conf. This prevents leakage of DNS results as
described in #1421.
This commit also adds an option to the `dns configure` command for
adding upstream DNS servers. Adding an upstream server simply adds a
nameserver entry to the (initially non-existent) resolve.conf file
dnsmasq is configured to use. Upstream servers added will immediately be
recognized by dnsmasq since it polls the file for changes.
closes #1421

[minimega] Prevent dnsmasq from leaking DNS results

---

cmd/minimega/deploy.go
cmd/minimega/log.go
cmd/minimega/log_cli.go
cmd/minimega/main.go
cmd/minimega/meshage.go

The new flag is `-lognode` and takes the name of a node on the mesh.
When minimega is deployed to other nodes using `deploy launch` the flag
will automatically be included using the hostname the deployment is
being run from.

[minimega] Add flag for sending logs to a node via the mesh

---

cmd/minimega/cc_cli.go
cmd/minimega/cli.go
cmd/minimega/command_meshage.go
cmd/minimega/command_socket.go
cmd/minimega/dot.go
cmd/minimega/misc_cli.go
cmd/minimega/namespace.go
cmd/minimega/namespace_cli.go
cmd/minimega/vm_cli.go
cmd/minimega/vms.go
doc/content/articles/developer/locking.article

There are cases where one mesh node sends commands to another, and while
waiting for the other node to respond it sends the original node a
command as well and waits for it to respond, leading to a blocking race
condition. Below is an example:
When adding a network interface to an existing VM using "vm net add",
the node the "vm net add" command is executed on sends a command over
the mesh to the node the VM is running on and waits for a response.
```
vm net add
head --------------> compute
```
When the compute node adds the network interface to the VM, it checks to
see if the VLAN alias for the interface exists. If it doesn't, it
creates the Alias-to-ID mapping and publishes it out to all the nodes in
the mesh and waits for a response.
```
vlans add
head <-------------- compute
```
This …

Use channel instead of mutex to serialize cli and meshage commands

---

cmd/minimega/cc_cli.go
cmd/minimega/cli.go
cmd/minimega/command_socket.go
cmd/minimega/iomeshage.go
cmd/minimega/main.go
cmd/minimega/meshage.go
cmd/minimega/misc_cli.go
cmd/minimega/namespace.go
cmd/minimega/status.go
cmd/minimega/vms.go
doc/content/articles/developer/status_updates.article
internal/iomeshage/handler.go
internal/iomeshage/iomeshage.go
pkg/miniclient/client.go

A new "status update" construct was added to provide long running
commands the ability to periodically send status updates about the long
running command to one or more nodes in the mesh.
A "status update" API command was added to allow users to adjust how
often, if at all, status updates are sent.
A developer article was added to help developers understand how the
construct was added and how it can be used.
While testing status updates, it was discovered that a lot of error logs
were being generated for things that weren't actually errors, so that
was fixed as well.

[minimega] Periodically publish status of file transfers

---

cmd/minimega/kvm.go

Adding USB 3.0 support through XHCI. Leaving in `-usb` and `-usb-ehci` QEMU flags for USB 1.1 and 2.0, respectively.

[minimega] Add USB 3.0 support

---

cmd/minimega/disk.go
cmd/minimega/kvm.go

This PR adds support for newer versions of QEMU, which had some backwards-compatible parameters. This closes #1485.

Add support for newer versions of QEMU

---

internal/iomeshage/iomeshage.go

Right now, using `file get` against a directory fails if there's only one node in the mesh. In general, if only one node exists, then obviously all files will be present on the node, so the `file get` process can be skipped.

[iomeshage] Short-circuit file get process if there's only one mesh node

---

cmd/pyapigen/template.go

The Python command `' '.join([str(v) for v in cmd if v])` will exclude command args that are `0`, which breaks, for example, capturing traffic on interface 0 of a VM.
Instead, use test `if v is not None`. This will allow empty strings to get through, but that shouldn't cause a problem.

[pyapigen] Allow zeros in minimega command args

---

cmd/minimega/disk.go

Lately we've been seeing a lot of `desired partition <n> not found` errors when injecting files into VM disk images. Adding this retry with backoff has proven to help reduce how often we see this issue (basically we don't see it anymore at all).

[minimega] Retry (with backoff) finding disk partitions for injects

---

cmd/minimega/cc_cli.go
cmd/rond/handlers.go
docker/Dockerfile
internal/ron/command.go
internal/ron/server.go

This allows, for example, the `shutdown -r now` command to be sent to a VM using command and control without putting the VM into a perpetual reboot loop. This is a contrived example, since a minimega VM can be rebooted without using command and control, but it still gets the point across. There may be other commands that are sent via command and control that end up causing a VM to reboot that would benefit from this as well.
New cc commands added:
cc exec-once command...
cc background-once command...

ron: add option for only executing a command once

---

cmd/minimega/main.go
docker/start-minimega.sh

This is useful for avoiding VLAN ID ranges that are used for production or lab networks that minimega may be tied into for hardware-in-the-loop access to real devices/workstations/servers.
The default for the flag is the same as the current default range, so not setting the flag provides backwards compatibility.

minimega: add CLI flag for setting default VLAN range for namespaces

---

cmd/minimega/namespace.go

When unmounting a VM's file system using `clear cc mount`, don't immediately return on errors, but instead log the error and allow the remaining commands to still attempt to be run.

[minimega] Log error instead of returning if cc mount path can't be unmounted

---

internal/ron/server.go

Continually reconnecting to an older version of miniccc that doesn't maintain a connection (mainly an issue in Windows VMs) prevents mounting the VMs file system using `cc mount` from working properly and in some cases will lock up the entire minimega process completely.

[minimega] Cancel serial connection retries if miniccc agent is too old

---

cmd/minimega/capture_cli.go

When deleting a netflow capture, the bridge name was getting assigned to the `<name>` variable but the code that deletes the capture was trying to get the name of the bridge from the `<bridge>` variable.

[minimega] fix bridge variable so deleting netflow capture works

---

cmd/minimega/cc_cli.go
internal/minitunnel/forward.go
internal/minitunnel/minitunnel.go
internal/ron/tunnel.go

Track and display port forward tunnels created using miniccc, and allow for existing tunnels to be torn down.

[minitunnel] track tunneled ports for listing and closing

---

docker/Dockerfile

The issue in #1527 can be solved by changing the docker base image from Ubuntu 20.04 to 22.04. This will change the QEMU version from 4.2 to 6.2 which will resolve the problem as described within the previous pull request #1528.

Changed Docker OS from 20.04 to 22.04

---

docker/Dockerfile

This is in support of rebuilding the minimega Python package in Docker images based off of this image. This is done, for example, in the sandia-labs/sceptre-phenix Docker image.
The Python package was updated to require this file in commit 1a428a9c.

[minimega] copy global VERSION file to lib directory in Docker image

---

cmd/minimega/kvm.go
cmd/minimega/vm.go
cmd/minimega/vm_cli.go
cmd/vmbetter/main.go
internal/qmp/qmp.go
internal/ron/server.go
internal/vnc/decode.go
internal/vnc/keysym.go

Bug fixes:
* Don't try typing extended vnc clipboard commands (fixes warning on connection to vm)
* Update debian mirror in vmbetter (closes #1529)
* Fix tpm qemu arguments for newer qemu versions
* Add bidirectional-copy-paste to "vm info" output
* Fix `vm clear tag <vm> <tag>` not applying to a specific tag (closes #1535)
* Fix `vm cdrom change` for QEMU 6+
Logging Improvements:
* Print hex for keysym character that couldn't be found
* Print hostname in "mismatched miniccc" warning
* Include qemu std err in "unable to connect to qmp socket" error

Misc bug fixes and logging improvements

---

cmd/minimega/misc_cli.go

Adds a command to print the CLI arguments minimega is using. 
This is being added so other programs (e.g., phenix) have any easy way to identify paths, ports, etc. Specifically this will replace phenix using `ps` to determine the `filepath`: https://github.com/sandialabs/sceptre-phenix/blob/main/src/go/util/file.go#L32

Add command to print arguments in use

---

docker/README.md
docker/start-minimega.sh

Instead of adding every flag to the `start-minimega.sh` script, this allows users to add whatever they need to the minimega startup command. Useful for appending additional minimega flags at runtime, e.g.:
```
MM_APPEND: -hashfiles -headnode=foo1
```

docker: add MM_APPEND env var

---

cmd/minimega/shell.go

Adding cli commands to view the status of `background` shell commands. When a call to `background [cmd]` is executed, mm stores the associated command alongside a sequential ID and some information (time start, time end, stdout, stderr, running). When the process exits, the stdout and stderr outputs are saved and the process is marked as complete. Users can then grab the stdout or stderr of a completed process. There is a limit of 50 background processes stored in the status table. When the 51st is created, the oldest (sorted by time of the process ending) will be removed from the table and stdout / stderr can no longer be accessed using `background-output`. All outputs of background processes are also logged to the logger on level info. 
Commands changed:
- `background`
- Now returns an …

Add new background commands

---

cmd/minimega/disk.go
cmd/minimega/misc.go

Adds the ability to delete files while doing disk inject via a keyword as the src. E.g.:
`disk inject window7_miniccc.qc2 files "-DELETE-":"Program Files/miniccc.exe"`

feat: allow disk inject to delete files

---

.github/workflows/docker.yml
docker/Dockerfile

This PR cleans up the dockerfile by using a well-supported docker metadata github-action to automatically generate most container tags and labels.
```json
"Labels": {
"org.opencontainers.image.authors": "minimega dev team \u003cminimega-dev@sandia.gov\u003e",
"org.opencontainers.image.created": "$${ steps.build_metadata.outputs.buildtime }}",
"org.opencontainers.image.description": "minimega is a tool for launching and managing virtual machines",
"org.opencontainers.image.documentation": "https://www.sandia.gov/minimega/",
"org.opencontainers.image.licenses": "GPL-3.0-only",
"org.opencontainers.image.ref.name": "ubuntu",
"org.opencontainers.image.revision": "04215d1c2d2e6b7d78630ff7dcae2adb94df3dd3",
"org.opencontainers.image.source": "https://github.com/sandia-minimega/minimega", …
```

refactor: Move docker labeling data to the CI pipeline

---

internal/nbd/nbd.go

There appears to be a race condition with the use of nbd devices during the `mm disk inject` command when running multiple disk injects in rapid succession (like starting a phenix experiment).
The error looks like this:
```bash
Starting Experiment
Starting experiment xxxxx
Mar  6 15:56:47.268 INF [✓] 'ntp' default app (pre-start)
Mar  6 15:56:47.270 INF [✓] 'serial' default app (pre-start)
Mar  6 15:56:47.299 INF [✓] 'startup' default app (pre-start)
Mar  6 15:56:47.312 INF [✓] 'vrouter' default app (pre-start)
Mar  6 15:56:47.778 INF [✓] 'mgmt_tap' user app (pre-start)
Mar  6 15:56:47.884 INF [✓] 'mirror' user app (pre-start)
Mar  6 15:56:48.648 INF [✓] 'sceptre' user app (pre-start)
Mar  6 15:56:48.662 INF [✓] 'scorch' user app (pre-start)
phenix 2025/03/06 15:56:54 …
```

Fix race condition with nbd sockets during disk injection

---

cmd/minimega/container.go
cmd/minimega/kvm.go

This bug fix enables VMs/containers to have the name "vince" while still honoring the initial intent of the easter egg within the code base: https://github.com/sandia-minimega/minimega/commit/a1e84558a9bb5a6f07107a417af3fd2bd11fe6cc.

fix: Allow VMs/containers with a certain name.

---

cmd/minimega/disk.go

In larger experiments (300+ VMs), this action fails to find partitions on the image. I believe increasing the number of possibles may patch this issue while investigate root causes. Performance issues may be hindering the ability for large experiments to find these objects and cause it to fail. Increasing this count will allow greater chance for success. Better handling may improve the experience instead of failing out of an experiment launch entirely.

Update disk.go with more attempts to find partitions

---

docker/Dockerfile

This PR includes the tool binaries in the docker image.
While this includes some tools like "minitest" that usually aren't needed in a deployment, the disk utilization difference is minimal, and this ensures any future tools get included in the Docker image. It also simplifies the Dockerfile a bit (less commands and potentially less layers).
8 binaries in `/opt/minimega/bin/` in final image, vs 26 binaries in `/minimega/bin/` directory as build outputs. 18 binaries NOT being included. `bin/` is 67 MB in current minimega image, vs 136MB in build output. That's a 69MB difference, which is relatively small.
`rfbplay` requires `ffmpeg`, which increases the image size by a bit (230MB or so), so I'm making a separate PR for adding ffmpeg to elicit debate about if that's worth adding.
Image …

fix: include tools in docker image

---

cmd/miniccc/dial.go

Fix tailing space in comment (from my PR #1579)  breaks the `gofmt` check in scripts/check.bash

fix: Remove tailing space in comment

---

docker/Dockerfile
docker/README.md
docker/start-minimega.sh

This PR adds new functionality to the docker `start-minimega.sh` entrypoint script:
- Adds better logging and error handling
- Adds an `OVS_APPEND` env var that supports a use case of using an external OVS server instance, with this being used as strictly a client. Some example minimega log output is below
- Adds a wait loop to ensure openvswitch is available before attempting to create a bridge and/or ports
* Without the wait, it's possible the bridge/port may not get created even if one passed in the correct [env variable](https://github.com/sandia-minimega/minimega/pull/1576)
Example minimega log output:
- docker compose deployment, external OVS server, without passing OVS_APPEND:
- docker compose deployment, external OVS server, with passing `OVS_APPEND: --no-ovsdb-server …

feat: better docker logging and error handling
